### ISSUE TITLE
Collection names are duplicated

### ISSUE THREAD

**Issue by drnextgis** [radiantearth/stac-browser#103]
I'm running stac-browser v3 locally and pointing it at a private test stac catalog:
```
$ npm start -- --open --catalogUrl="https://stac-api.local
```

The catalog has 2 collections but stac-browser shows them two times:
![image](https://user-images.githubusercontent.com/866124/138372124-de3d9160-288a-478d-b37d-b6328a79d3ee.png)

As you can see names of collections are the same but its URLs a bit different:

* http://localhost:8080/collections/my-collection
* http://localhost:8080/http:/stac-api.local/collections/my-collection

**Comment by m-mohr** [comment]
This has been fixed, but may get another change once the issues above have been tackled in the API spec.

**Comment by drnextgis** [comment]
Thanks!
