### ISSUE TITLE
e.getLinkWithRel is not a function

### ISSUE THREAD

**Issue by AsgerPetersen** [radiantearth/stac-browser#105]
Top reproduce:

1) Go to https://radiantearth.github.io/stac-browser
2) Open https://data.geo.admin.ch/api/stac/v0.9/ in STAC Browser (but it seems to fail with any API)
3) Click the collection `swissALTI3D`
4) Click `Next` to get next page of items.

Next page is not shown. Instead the error below is shown

![image](https://user-images.githubusercontent.com/1392735/142778908-4f97835f-934b-448b-888f-9eb4af99b686.png)

**Comment by m-mohr** [comment]
Thanks for reporting, it seems I failed to resolve a merge conflict properly. Will fix asap.

**Comment by m-mohr** [comment]
While fixing this bug, I found out that your API implementation also has an issue:
Some parent links point to invalid links. All links with relation type "parent" must point to valid Catalogs or collections, but some point to a list of collections or items.
Examples:
- https://data.geo.admin.ch/api/stac/v0.9/collections/ch.swisstopo.geoidmodell-ch1903 has a parent link to http://localhost:8080/external/data.geo.admin.ch/api/stac/v0.9/collections, but it should point to http://localhost:8080/external/data.geo.admin.ch/api/stac/v0.9/
- http://localhost:8080/external/data.geo.admin.ch/api/stac/v0.9/collections/ch.swisstopo.geoidmodell-ch1903/items/geoidmodell-ch1903 has a parent link to http://localhost:8080/external/data.geo.admin.ch/api/stac/v0.9/collections/ch.swisstopo.geoidmodell-ch1903/items although it should point to http://localhost:8080/external/data.geo.admin.ch/api/stac/v0.9/collections/ch.swisstopo.geoidmodell-ch1903

Hope that helps!

**Comment by m-mohr** [comment]
@AsgerPetersen The issue should be fixed, please let me know if you still encounter issues. Thanks!

**Comment by p1d1d1** [comment]
@m-mohr many thanks for the fix and for highlighting the issue with the parent links.
