### ISSUE TITLE
Stac-Browser fails to load item pages from top level catalog

### ISSUE THREAD

**Issue by dlindenbaum** [radiantearth/stac-browser#11]
For the SpaceNet Catalog It currently has a single catalog with items listed.

To reproduce the problem: 
The stac-browser is deployed at:
1. https://vigilant-heyrovsky-0d9af8.netlify.com/

2. CLick on AOI_2_Vegas_MUL-PanSharpen and it goes to a blank page

3.  If you go directly to the page and it loads. https://vigilant-heyrovsky-0d9af8.netlify.com/item/AOI_2_Vegas_MUL-PanSharpen_Cloud

4.  Of if you hit refresh.

**Comment by mojodna** [comment]
The SpaceNet catalog now renders properly (despite the occasional validation issue): https://spacenet.stac.cloud
