### ISSUE TITLE
Restrict number of items retrieved by default?

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#118]
By default, STAC Browser retrieves as many Items and Collections from APIs as the server returns by default. This can be quite a huge number of items and as such it gets overwhelming quickly. Also, it's not so easy to scroll down to other sections that are shown below. So I'm wondering whether we should limit the number of items (and/or collections) shown by default, e.g. to 15 Items and 50 collections?

**Comment by m-mohr** [comment]
itemsPerPage option implemented, leaving this open for collections and feedback.

**Comment by rowanwins** [comment]
I think the defaults implemented are sensible. 
Another option could also be to add a dropdown on the UI allowing the user to select the page size (eg 12, 24, 48).

**Comment by m-mohr** [comment]
For API Items there's actually an option available via the "Filter" capabilities:

![grafik](https://user-images.githubusercontent.com/8262166/161156738-62d3836c-10e5-4d01-ab0f-f32b8ee3e18f.png)

It is a bit hidden though, but that's probably a good thing as it's likely more an option for advanced users and you usually don't want to be bothered by it.
