### ISSUE TITLE
Support query params in STAC urls

### ISSUE THREAD

**Issue by zakjan** [radiantearth/stac-browser#121]
If there are query parameters in STAC urls such as `?access_token=xxx`, they are appended to frontend links as-is, and they are not sent to STAC backend when navigating in stac-browser v3.

I can see two options how to handle this:
- add `catalogUrlParam` config option for common params, strip them in `toBrowserPath`, add them back in `fromBrowserPath`. This produces cleaner urls, but requires that the params are the same across the catalog. (my current approach)
- replace `?` with any other markup in `toBrowserPath`, replace back in `fromBrowserPath`. This would be more universal.

What's preferred?

**Comment by m-mohr** [comment]
I need to look a bit closer into this, I also have some query parameter-related issues on my to do list. For example, I'd like to make pagination information in the URL, too. Your second option seems too "aggressive" though and may conflict with other use cases for query parameters, I think.

**Comment by zakjan** [comment]
I can send a PR with `catalogUrlParam`, if it helps. I understood that there are more features to consider though.

**Comment by zakjan** [comment]
Here is a commit for inspiration about the static params. https://github.com/weatherlayers/stac-browser/commit/a2623ac41e4229488b7f3abf9d89156204a49ead However, I realised that such static params is probably incompatible with signed S3 and similar URLs. Is it an issue?

**Comment by zakjan** [comment]
@m-mohr Thanks for the update. Even though I'm mostly involved in the first case, the other cases are important as well.

The access token is actually public, not private. Disclosing the access token publicly is a known and controlled risk. It's commonly used in map tile APIs, Mapbox, Google Maps, many others. The token can be optionally origin-restricted, to make its misuse harder, but it's not perfect.

It's great that you are trying to hide the token, but there is probably no need to spend much time on it. As long it's hidden from a regular user and URLs look clean, it's fine.

> This parameter should not be passed to the "Share" functionality, e.g. if you want to share a URL via Twitter.

You're right, but sharing a URL without the param seems it's of no use, if the shared URL can't be opened by anyone else.

---

Re your current implementation:

The catalog URL and the token are configurable in separate places, even though they are supposed to be together. Is there a reason for that?

Currently my catalog copies the token from the request to links for easier navigation. It causes that collection/item card links generated as-is, the token is not striped away from them. Do you know if there is a STAC spec recommendation about this, include the token in links or not?

To be considered, compatibility with `--historyMode=hash`. It's used for a Vue build served from a static file storage. Currently it works, but params after `?` are sent to the server, which is unnecessary.

**Comment by m-mohr** [comment]
> The access token is actually public, not private.

Might be in your case, but that's not always the case.

> > This parameter should not be passed to the "Share" functionality, e.g. if you want to share a URL via Twitter.
> 
> You're right, but sharing a URL without the param seems it's of no use, if the shared URL can't be opened by anyone else.

Then you are probably interested more in case 2 rather than 1? Anyway, the current implementation doesn't even provide sharing functionality if a private token was given. It's disabled then.

> The catalog URL and the token are configurable in separate places, even though they are supposed to be together. Is there a reason for that?

Why are they supposed to be together? catalogUrl is usually a global option, the token is often user-specific so I don't think they should be together.

> Currently my catalog copies the token from the request to links for easier navigation. It causes that collection/item card links generated as-is, the token is not striped away from them. Do you know if there is a STAC spec recommendation about this, include the token in links or not?

No, there is none afaik. STAC does not talk about authentication details. It's up to implementers to follow best practices in the respective fields.

> To be considered, compatibility with `--historyMode=hash`. It's used for a Vue build served from a static file storage. Currently it works, but params after `?` are sent to the server, which is unnecessary.

Indeed, that's not ideal. We should probably consider adding private information to the hash if possible.

**Comment by m-mohr** [comment]
I don't understand that point. Can you clarify why a backend proxy is needed?

**Comment by zakjan** [comment]
A private token shouldn't be exposed to frontend, it can be used by backend only. Or what else is the difference between a public and private token?

**Comment by m-mohr** [comment]
I think we are talking about different things here. This is not meant to be published, a user would need to provide it to the client. That's why it's in the URL, not in the config.

**Comment by zakjan** [comment]
Ah, ok I see. Then it's more similar to allowing external catalog URLs, there could be a user input for it as well.

**Comment by m-mohr** [comment]
Yes, but it would need two inputs as you also need to provide the key.

**Comment by m-mohr** [comment]
The issues raised above should be fixed.

**Comment by m-mohr** [comment]
I'd consider this being solved. Point 3 of my list above (state query parameters) will be tackled separately. If any new issues appear, please report them specifically in a new issue. Thanks.
