### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by p1d1d1** [radiantearth/stac-browser#123]
Is there any plans to implement multilingual support?

**Comment by m-mohr** [comment]
Not yet, STAC Browser depends on a couple of packages that are not multi-lingual yet so this is a major effort across multiple packages and will likely only appear in version 3.1 or later.

**Comment by m-mohr** [comment]
Additional interesting use case: Filter/Prioritize assets in STAC Browser based on the language set via the language flag: https://github.com/radiantearth/stac-spec/issues/1190

**Comment by m-mohr** [comment]
Libraries that potentially need to be translated for STAC Browser to be fully multi-lingual:

- [ ] STAC Browser itself (probably via vue-i18n)
- [ ] stac-fields
- [ ] stac-migrate
- [ ] stac-layer
- [ ] leaflet / vue2-leaflet
- [ ] leaflet-fullscreen / vue2-leaflet-fullscreen
- [ ] bootstrap-vue
- [ ] v-clipboard
- [ ] vue-read-more-smooth
- [ ] vue2-datepicke

**Comment by m-mohr** [comment]
@p1d1d1 A first version of language support has been merged into the dev branch. You could consider adding the Italian language files from now on. :-)

**Comment by m-mohr** [comment]
ToDos:
- [ ] Add missing German phrases
- [ ] Fix issue that the browser detected language is only applies to the UI
- [ ] Implement #231
- [ ] Final tests
