### ISSUE TITLE
License is not displayed

### ISSUE THREAD

**Issue by drnextgis** [radiantearth/stac-browser#124]
My stac items have `license` property with a short text but stac browser doesn't show it:

![image](https://user-images.githubusercontent.com/866124/154095844-20ee7ed1-6b4f-40f7-9d7b-a3929eb12aa8.png)

**Comment by m-mohr** [comment]
The license field in STAC is not allowed to contain custom text. You need to link to custom licenses.

**Comment by drnextgis** [comment]
According to the docs:
> use `proprietary` (see below) if the license is not on the SPDX license list or `various` if multiple licenses apply

I've updated my STAC items to have `proprietary` license but stac browser still shows it as `n/a`, don't you think that it can be improved to distinguish items without license and proprietary ones?

**Comment by m-mohr** [comment]
Indeed, if proprietary or various is given and no link is provided there's an issue. I can show "proprietary" and "various", will fix that. I'd recommend linking to a license though.
Otherwise, I'll follow the spec and not encourage invalid STAC files.

**Comment by m-mohr** [comment]
Fixed in stac-fields, will be available in the next release of STAC Browser (probably v3.0.0-alpha.7).

**Comment by drnextgis** [comment]
Thanks!
