### ISSUE TITLE
Broken tile.rdnt.io URL

### ISSUE THREAD

**Issue by drwelby** [radiantearth/stac-browser#126]
https://radiantearth.github.io/stac-browser/#/external/ard.maxar.com/samples/v4/sample-001/10/120020223032/2016-10-08/103001005D31F500.json

On initial page load either `stac-browser` or `stac-layer` is trying to use the Radiant tiler but the URL isn't right:

`https://tiles.rdnt.io/tiles/10/163/395@2x?url=https%3A%2F%2Fard.maxar.com%2Fsamples%2Fv4%2Fsample-001%2F10%2F120020223032%2F2016-10-08%2F103001005D31F500.json%2F103001005D31F500-clouds.tif`

It's appending the asset name to the parent Item location.

**Comment by m-mohr** [comment]
Thanks for reporting. Probably a STAC Browser issue that got broken in the recent URL/query parameter re-work. I'll check.

**Comment by m-mohr** [comment]
Actually, seems to be a stac-layer issue. Moving it over...

**Comment by m-mohr** [comment]
> https://radiantearth.github.io/stac-browser/#/external/ard.maxar.com/samples/v4/sample-001/10/120020223032/2016-10-08/103001005D31F500.json
> 
> On initial page load either `stac-browser` or `stac-layer` is trying to use the Radiant tiler but the URL isn't right:
> 
> `https://tiles.rdnt.io/tiles/10/163/395@2x?url=https%3A%2F%2Fard.maxar.com%2Fsamples%2Fv4%2Fsample-001%2F10%2F120020223032%2F2016-10-08%2F103001005D31F500.json%2F103001005D31F500-clouds.tif`
> 
> It's appending the asset name to the parent Item location.
