### ISSUE TITLE
Better search support

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#128]
- [CQL / Fiilter](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/filter) - more fine grained search with a nice UI for constructing the filters.
- [Context](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/context) - make use of the context information, if present.
- Support reading queryables, e.g. for [sort](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/sort) to show all fields that you can sort on
- ...

**Comment by rowanwins** [comment]
I've started tinkering on this
- [x] Retrieving queryables from endpoint

In terms of the UI my current approach is 
- present a dropdown of the available fields/properties
- Display an appropriate form input based on the field type determined from the queryables info
- Show a number of comparators for the field

https://user-images.githubusercontent.com/6735870/163924697-e7a9205c-0f25-43c0-9276-b44ab2d3373c.mp4

What do you think of this sort of direction @m-mohr ?

**Comment by m-mohr** [comment]
This looks pretty good to me. I'll also ask @jsiarto what he thinks in the next days.

We may need to fine-tune some details, e.g. the label for the field doesn't match the label in the select box and the gray of the box doesn't match the gray of the other boxes. But overall looks good to me, thanks for showing it.

**Comment by m-mohr** [comment]
Actually, the buttons belong to the whole filter section so don't make a lot of sense in the card that is shown. Either the card needs to be extended or even removed?

**Comment by m-mohr** [comment]
Closing this in favor of more concrete issues.
