### ISSUE TITLE
Broken base64 in leaflet map for Point geometry

### ISSUE THREAD

**Issue by itcarroll** [radiantearth/stac-browser#139]
Items with `Point` geometry render with an error in the leaflet map. The python snippet below produces a single item demonstrating the problem. Served from localhost and opened in Chrome with https://radiantearth.github.io/stac-browser/#/external/http:/localhost:8080/test.json, I get the console error `Failed to load resource: net::ERR_INVALID_URL`. The base64 string in the broken image's `src` attribute ends with `=")marker-icon.png`, which doesn't look so good.

```
from pystac import Item
from shapely import geometry
from datetime import datetime

geom = geometry.Point((0, 0))
#geom = geometry.Polygon(((0, 0), (0, 1), (1, 1), (1, 0), (0, 0)))
item = Item(
    id='test',
    geometry=geometry.mapping(geom),
    bbox=geom.bounds,
    datetime=datetime.now(),
    properties={},
)
item.save_object(dest_href='build/stac/test.json')
```

With the `Polygon` geometry (in comment) replacing the `Point`, everything looks good.

@m-mohr Suggested this is likely a problem with stac-layer, but I can't confirm that because I don't use stac-layer directly.

**Comment by m-mohr** [comment]
@itcarroll Thanks. stac-layer is always used in stac-browser, so you are likely using it anyway. I'll check this in the next days and verify where it originates from and hopefully come up with a fix.

**Comment by m-mohr** [comment]
Found the issue in vue2-leaflet: https://vue2-leaflet.netlify.app/quickstart/#marker-icons-are-missing

Fixed in https://github.com/radiantearth/stac-browser/commit/dd69328e8c20cd224c5c3d84a8dc9cbebd73bff3
