### ISSUE TITLE
Providers link directly on provider's name

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-browser#143]
It would be useful to have the Providers list just as a simple list of titles, each one clickable. 

At the moment the "go to homepage" button can be seen only after a click and isn't very intuitive.

Here a simple example on how it could look like:
![image](https://user-images.githubusercontent.com/98519154/162435076-d6a17eea-b274-4106-b474-a0bf364a3c55.png)

**Comment by jclark-indigoag** [comment]
+1 looks cleaner!

**Comment by m-mohr** [comment]
That doesn't work too well because providers can have additional metadata although they rarely have. Then you need a way to expand the box...

**Comment by chiarch84** [comment]
But since those information are short (and rarely used) couldn't  they be placed as text right below the Provider's name and be always shown without having to open or close a box to see those information? This way you can keep the link on the Provider's name.

**Comment by m-mohr** [comment]
No, they are not necessarily short. I'll think about a solution that covers both cases.

**Comment by m-mohr** [comment]
Has been implemented in a way that if none of the providers has additional metadata, then it's a list with links.

**Comment by chiarch84** [comment]
I like it much better now, even though I think it should have the same layout as the other lists.
Here I post an example of how it comes out now:

![image](https://user-images.githubusercontent.com/98519154/162736682-e9c3826b-8148-4ce4-815b-67862b794e8b.png)

**Comment by m-mohr** [comment]
Which other lists are you referring to?
- The "Additional resources"? This is indeed a "plain" list and I'm not 100% sure why the listgroups in Bootstrap don't look like a list to be honest.
- The assets look exactly like the providers, I think.
- The metadata is a table.


What do you mean with "3 more borders"?

**Comment by chiarch84** [comment]
Thanks for checking it out. At the moment to me it sound a little strange to see the 2 sides different, but I'm not a GUI expert. It's just user experience point of view. Thanks

**Comment by m-mohr** [comment]
@jsiarto Thoughts?

**Comment by jsiarto** [comment]
These are _technically_ two different components (list/dl vs a table row)--so it's not unusual for them to be different. But I agree that we may want to add some consistency across the different types (alternative row grey with the top border)

**Comment by m-mohr** [comment]
After some discussions, we agreed on adding a border to the metadata boxes so that they align a bit more, hope you like it @chiarch84?

![grafik](https://user-images.githubusercontent.com/8262166/164542390-33a010c3-17fd-4e35-9a57-879642ca56c3.png)

**Comment by chiarch84** [comment]
That's ok then! Thanks for the effort!
