### ISSUE TITLE
Asset href: PATH URI

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-browser#144]
Following what described in the STAC item specs. The asset href can be either an absolute or a relative URI.

URI though shouldn't mean that it has to be an URL.

In our use-case for example, we have all the assets available on a distributed filesystem that is reachable form all the users of our platform and the TIF, SHP, VRT etc. files are not meant to be downloaded but used from the users where they are. 

Through the metadata we want to give them the exact location on the filesytem (Path). 

With the actual GUI though a download button automatically appears by adding to our PATH the STAC Browser base url, creating a broken link.

**Comment by m-mohr** [comment]
Could you give an example, please? Ideally a catalog that I can look at?

**Comment by chiarch84** [comment]
Sure, here is a json example (Sorry but the catalog is for internal use of our Organization only):
```json
{
    "stac_version": "1.0.0",
    "type": "Feature",
    "stac_extensions": [],
    "id": "Landcover.ESA.WorldCover2020.V1.item.1",
    "bbox": [
        -180,
        -90,
        180,
        90
    ],
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    -180,
                    90
                ],
                [
                    180,
                    90
                ],
                [
                    180,
                    -90
                ],
                [
                    -180,
                    -90
                ],
                [
                    -180,
                    90
                ]
            ]
        ]
    },
    "properties": {
        "title": "ESA_WorldCover_10m_2020_v100_Map.vrt",
        "description": "The ESA WorldCover Team is proud to announce the successful development of a new baseline global land cover product at 10m resolution that is developed and validated in almost near-real time and at the same time maximizes the impact and uptake for the end users. Inspired by the 2017 WorldCover conference organized by ESA, the cardinal requirements of the WorldCover project are: fast generation and validation of a world land cover based on Sentinel-2 and Sentinel-1 constellations 10 land cover classes 10 meters resolution, 75% overall accuracy. The WorldCover products are delivered in a regular latitude/longitude grid (EPSG:4326) with the ellipsoid WGS 1984 (Terrestrial radius=6378 km). The legend includes 11 generic classes that appropriately describe the land surface at 10m: Tree cover, Shrubland, Grassland, Cropland, Built-up, Bare / sparse vegetation, Snow and Ice, Permanent water bodies, Herbaceous Wetland, Mangrove and Moss and lichen.",
        "start_datetime": "2020-01-01T00:00:00Z",
        "end_datetime": "2020-12-31T23:59:59Z",
        "datetime": null
    },
    "collection": "Landcover.ESA.WorldCover2020.V1",
    "links": [
        {
            "rel": "collection",
            "href": "https://jeodpp.jrc.ec.europa.eu/eu/data/Base Data/Landcover/Landcover.ESA.WorldCover2020.V1.json",
            "type": "application/json"
        },
        {
            "rel": "parent",
            "href": "https://jeodpp.jrc.ec.europa.eu/eu/data/Base%20Data/Landcover/Landcover.ESA.WorldCover2020.V1.json",
            "type": "application/json"
        },
        {
            "rel": "root",
            "href": "https://jeodpp.jrc.ec.europa.eu/eu/data/catalog.json",
            "type": "application/json"
        },
        {
            "rel": "self",
            "href": "https://jeodpp.jrc.ec.europa.eu/eu/data/Base%20Data/Landcover/Landcover.ESA.WorldCover2020.V1.item.1.json",
            "type": "application/json"
        }
    ],
    "assets": {
        "data": {
            "href": "/eos/jeodpp/data/base/Landcover/GLOBAL/ESA-WorldCover/2020/VER1-0/Data/VRT/ESA_WorldCover_10m_2020_v100_Map.vrt",
            "type": "application/x‐ogc-vrt",
            "title": "Dataset",
            "roles": [
                "data"
            ]
        }
    }
}
```

**Comment by m-mohr** [comment]
Thanks. Yeah, I can't distinguish with such URIs whether they are URLs or URIs and whether I need to convert them for HTTP usage or not. Any ideas?

**Comment by chiarch84** [comment]
Thanks for the suggestion! I think that using `file:/` would be a good solution. This way you can just show the value of the path if the prefix `file:` exists, instead than creating a download button. Thank you!

**Comment by m-mohr** [comment]
Right now the `file:` protocol would still show a download button though, but it would not modify the URI so that you can copy the correct URI via the context menu of the browser. Without additional context, it is not clear for the Browser whether the file URLs would be available for users or not. I assume I could implement a blacklist for downloadable protocols so that for all black-listed protocols you'd get a copy button instead.

**Comment by chiarch84** [comment]
To me the "Copy" button for specific protocols makes sense, because if it is a "download" button the user won't understand that he has to copy paste the url, he would just think that the download is not working.

**Comment by chiarch84** [comment]
Just one question. To see all your modifs which branch/es should I use? I always use the [v3](https://github.com/radiantearth/stac-browser/tree/v3) one, but I don't know if I should add some others to it, like for example [gh-pages](https://github.com/radiantearth/stac-browser/tree/gh-pages) or other.

**Comment by m-mohr** [comment]
v3 is the correct one to look at.
I've not applied any changes yet for this PR.

**Comment by m-mohr** [comment]
Support for file:// urls has been added:

![grafik](https://user-images.githubusercontent.com/8262166/172944714-cab71b2a-5877-4ba4-a7d4-a5b6c9cfa1a8.png)

**Comment by chiarch84** [comment]
I just checked the functioning now and in effect the button "copy url" correctly appears, but it seems that **there is a problem appearing on the items list of the collection itself.**

The **loading icon of the items** never disappears.

While if I go directly to the url of the item I don't get any problem in the visualization.

![image](https://user-images.githubusercontent.com/98519154/177174530-dd8022e6-26c0-4061-b9d0-c34695c94e02.png)

**Comment by m-mohr** [comment]
This is a new issue, I'll create a new issue for it. This is not public, right? Are there any outputs in the browser console?

**Comment by chiarch84** [comment]
I post on this issue since after 6 months of usage of this "functionality" I must say that the copy button is useful, but it would be also very useful to have the path shown as text.

Another thing is the protocol "file:/" in front of the path. We are at the moment storing the metadata in the DB directly with the "file:/" prefix, since adding it during the APIs response would end up in loosing a lot of time when the number of results is high. I don't really like though to have this prefix attached to the data because in every application/library using that value I always have to do a clean function to get the original value. I would prefer to just store and return the path itself. Isn't there another way to check weather an URI is also a URL or not? If it does not start with "http" then it should be just a URI or not?

**Comment by m-mohr** [comment]
> I must say that the copy button is useful, but it would be also very useful to have the path shown as text.

Indeed, I'll enhance this as part of #262.

> Another thing is the protocol "file:/" in front of the path. We are at the moment storing the metadata in the DB directly with the "file:/" prefix, since adding it during the APIs response would end up in loosing a lot of time when the number of results is high. I don't really like though to have this prefix attached to the data because in every application/library using that value I always have to do a clean function to get the original value. I would prefer to just store and return the path itself. Isn't there another way to check weather an URI is also a URL or not? If it does not start with "http" then it should be just a URI or not?

On Windows there might be a chance, but on *nix it is impossible afaik. `/path/to/file` can either be on a file system or part of another URI, I don't know how I could detect that. I guess we could remove the file:// when copying though...

**Comment by chiarch84** [comment]
Hmm I'm not very knowledgeable in this domain. I thought the URL always had to start with http or https so would have assumed all the rest is just a path. It is of course useful to avoid copying also the file:// but I would like to avoid storing this anyhow and also avoid returning it to the users through the APIs.

**Comment by m-mohr** [comment]
If a STAC document is served via HTTP(S) [which is required for STAC Browser], the base URL for the document is for example `https://whatever.com/api/`.
In links and assets you can now provide a path, e.g. `collections/1234`, `./collections/1234`, or `/api/collections/1234`.
These can all resolved to be `https://whatever.com/api/collections/1234` with the base URL.

At the same time `/api/collections/1234` is a completely valid absolute path on *nix systems. Without the `file://` prefix the Browser must assume that the context doesn't change (e.g. the protocol and host) and as such resolve them against the base URL.

This is the crux, which we can only solve by explicitly specifying file:// as protocol as otherwise https:// will be the basis.

**Comment by chiarch84** [comment]
and what about using the other attributes of the asset object to understand that? Maybe the role.

**Comment by m-mohr** [comment]
URIs are independant of STAC and as such don't know anything about roles or so.
You may propose a STAC extension to combine URI resolution with something like a role, but that would break implementations that are not aware of the extension. As such I'd not recommend that. What you are doing with file: is used everywhere in the digital world and completely normal. Try to open a local file in a browser, it will prepend the "file:" as well.

**Comment by m-mohr** [comment]
Actually, the file scheme is an international standard: https://www.rfc-editor.org/rfc/rfc8089

**Comment by chiarch84** [comment]
hmm ok, than probably it's fine.
Anyhow I think that showing the text of the URI would be good anyhow, independently if it's a download url or a local path url. and probably as you say, I would avoid printing "file://" or copying it

**Comment by m-mohr** [comment]
Yes, we'll improve this in the future, see issue #262.
Testing a bit more it seems most tooling I use is aware of file: - which software are you using that can't handle it?

**Comment by chiarch84** [comment]
well actually most people are using their own Python libs that get the path directly from the APIs.

**Comment by m-mohr** [comment]
That seems to be mostly a Python (ibrary) issue that needs to be solved by your people: https://discuss.python.org/t/file-uris-in-python/15600
I know that e.g. PHP, JavaScript (Node) and R accept file: URIs just fine.
