### ISSUE TITLE
Deprecated collections showing at the same time as non deprecated ones

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-browser#149]
It would be useful to "hide" deprecated collections from the list and tiles view and have a button to show /hide them (in case there are some).

t the moment for example I've got a list of many collections, each with version 1,2,3,4 and I would prefer to see at a glance all the ones that are not deprecated, rather than seeing all together deprecated and non deprecated ones.

**Comment by m-mohr** [comment]
Yeah, that is reasonable, but it seems that these are different use cases.

Deprecated originally was really meant to indicate that it is going to be removed. Your use case is more "superseded" or "outdated" (not 100% sure about the terminology). Thus, I'm wondering whether this should result in a new flag/field in the versioning extension? https://github.com/stac-extensions/version

Are you using the link relations types defined by the extension to link to the next or latest version? https://github.com/stac-extensions/version#relation-types
In this case we could also drop the use of the deprecated field and just add a badge in case a corresponding link is given.

**Comment by chiarch84** [comment]
Yes I'm using the links "latest-version" and "successor-version".

That would be nice to have a "superseded" badge (or a better term that at the moment I can't come up with) in case at least "latest-version" link exists and the collection is not deprecated. In this case, no need to add a new flag/field extension.

The same should happen in the collection itself. I would keep the yellow box that you created for "deprecated" collections but I would just change the text in case of "superseded" collection. Something like: "Please note that this Collection has newer versions available."

**Comment by m-mohr** [comment]
Yeah, also not sure about the terminology.

Ideas:
- outdated
- old version
- superseded

I like outdated most. If you have any ideas or preferences, please let me know.

I'll also have another look at the deprecated box with the links...

**Comment by chiarch84** [comment]
I'm not sure... all these terms put the enphasis on the fact that the collection is "old", it seems that it shouldn't be used. This though is not the purpose. Elevation data from 2020 can be as important as the one from 2022 or even more important in case a specific phenomenon could me highlighted only in 2020. 

In my opinion I would look more for something like "newer version available" even though I know it is kind of long. So something that could give this idea.

**Comment by m-mohr** [comment]
But if a newer version is available, aren't people then implicitly thinking that the version they are looking at is "old" anyway? At least I'd think it is old because a newer version is available. I'm not sure we can really get around this...

**Comment by chiarch84** [comment]
Actually "past version" sounds good to me! I would say that in my opinion it is the best to fit term until now.

But you can implement it as it is better for you.

**Comment by m-mohr** [comment]
Closing. Deprecated fits to the official description of the specification and it can now be customized pretty easily via the custom.json for translations. Just add: 

```
{
  "deprecated": "Past Version",
  "fields": {
    "Deprecated": "Past Version"
  }
}
```
