### ISSUE TITLE
Support a vendor field for displaying logo / images in catalogs

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-browser#16]
See https://github.com/radiantearth/stac-spec/issues/196

It'd be cool to enable catalog providers to do things like put a logo to be displayed. We can make a little STAC spec extension that we document in STAC Browser that we'll recognize. If other tools start to support it we can make it a more generic 'extension' for STAC.

**Comment by m-mohr** [comment]
I think you wanted to refer to issue https://github.com/radiantearth/stac-spec/issues/196 instead of 94.
