### ISSUE TITLE
Improve page transitions

### ISSUE THREAD

**Issue by trevorlang** [radiantearth/stac-browser#163]
Improve the loading state to create a more seamless transition between different pages. Preventing the collapsing of the page and centering the loading indicator should create an improved experience.

**Comment by m-mohr** [comment]
Might be relevant, too: https://router.vuejs.org/guide/advanced/transitions.html#route-based-dynamic-transition

**Comment by trevorlang** [comment]
This has been addressed in https://github.com/radiantearth/stac-browser/pull/181

@m-mohr, I was able to accomplish the improved layout with bootstrap using the existing template. Let me know if there is any loading states that I missed with this push.

**Comment by m-mohr** [comment]
That's a good first step. Let's see for 3.0.0 if we can further improve the situation.
