### ISSUE TITLE
Consider using a darker default primary color by default

### ISSUE THREAD

**Issue by trevorlang** [radiantearth/stac-browser#165]
The current primary color in the default template (`#17A2B8`) has a pretty low contrast ratio. Currently, the ratio is 3.04. This can be improved by darkening the primary color.

Something with the same hue, but a little darker  (ex: `#138495`) might work better.

**Comment by m-mohr** [comment]
Just for context: The color is the darkest color from the STAC logo :-)
But we are not bound to the STAC colors and can choose any color basically. I just changed the color to not use the default Bootstrap blue again.

**Comment by trevorlang** [comment]
I thought that might be the case. I don't hate the slightly darker version of the STAC color. It looks pretty "on-brand" in my opinion. But if we want to experiment with some other colors, we can definitely do that too.

**Comment by trevorlang** [comment]
This is addressed in https://github.com/radiantearth/stac-browser/pull/181
