### ISSUE TITLE
Add width and height to catalog, collection, and item thumbnails

### ISSUE THREAD

**Issue by trevorlang** [radiantearth/stac-browser#166]
If the thumbnails exist, a fixed width or height might improve the content shifting when loading. In a static catalog, it might be possible to check if thumbnails are defined on the catalogs, collections, or items. In dynamic catalogs, the height and width should be defined as soon as possible in order to prevent collapsing from causing issues with the lazy-loading.

**Comment by m-mohr** [comment]
As long as the height and width are not provided through the metadata, it's not available and as such can't be set. proj:shape could be a way to set it, but usually the thumbnails are not projected so you also need to set proj:epsg to null. It seems no one is doing that.

**Comment by m-mohr** [comment]
Will be done if proj:shape is specified.
