### ISSUE TITLE
Improve display of Items section when no items are loaded

### ISSUE THREAD

**Issue by trevorlang** [radiantearth/stac-browser#171]
The item's pagination should not be visible when no items exist. Instead, an improved empty state should be displayed. This could be a panel with the text "No items exist for this collection", or the items section could be removed entirely.

**Comment by m-mohr** [comment]
Done:

![grafik](https://user-images.githubusercontent.com/8262166/172950966-853a3d2f-1992-4230-9651-11cf1aaa9846.png)

As usual, if you think there's additional room for improvements, feel free to re-open.
