### ISSUE TITLE
Improve display of disabled pagination buttons

### ISSUE THREAD

**Issue by trevorlang** [radiantearth/stac-browser#172]
The disabled pagination buttons with no previous pages exist do not have a lot of contrast to the active buttons. The button style should be improved to make it more obvious which buttons are disabled. Consider also using a `cursor: not-allowed` when the disabled buttons are hovered.

**Comment by m-mohr** [comment]
Additionally, if no items are present at all, we can probably remove them completely.

**Comment by m-mohr** [comment]
This is a Bootstrap thing, so we should consider doing this globally and not only for pagination.
