### ISSUE TITLE
Use Boostrap tooltips instead of labels in metadata sections

### ISSUE THREAD

**Issue by trevorlang** [radiantearth/stac-browser#174]
The "GSD" label is underlined to indicate a tooltip is available. It is could be confusing that a `label` is being used to display the tip, due to the fact that it takes a few seconds for the label to appear. Consider using a bootstrap tooltip component instead.

**Comment by trevorlang** [comment]
I wonder if we could grab the URL dynamically add the style to the document that way. 

I'm a little new to Vue, but I assume this is something that could be achieved somehow.

**Comment by trevorlang** [comment]
Ah, that may be a challenge then. I may do some quick experimentation to see if there is a way to achieve it with the library.

**Comment by m-mohr** [comment]
In the long-term, we may want to decouple stac-fields and STAC Browser a bit more so that such things can be implemented.

**Comment by m-mohr** [comment]
As this is non-trivial, but on the other hand we are facing just the normal OS tooltip behavior that people should usually be aware of, I'm closing this.
