### ISSUE TITLE
Incorrect bbox calculation

### ISSUE THREAD

**Issue by drnextgis** [radiantearth/stac-browser#189]
The widget allows move the map across the 180° meridian. This results in an incorrect bbox calculation.

![image](https://user-images.githubusercontent.com/866124/176365139-e8d46236-8a3c-414d-b326-3a8781a66a4a.png)

**Comment by m-mohr** [comment]
Thanks for catching that, I'll fix that.

**Comment by drnextgis** [comment]
> Thanks for catching that, I'll fix that.
> 
> I also see that your list of collections is empty. Can you see why that is? Are you implementing /collections and expose collections there?

https://radiantearth.github.io/stac-browser/#/search/external/stac.amskepler.com/v100

**Comment by m-mohr** [comment]
Thanks, yeah, no collection endpoint so I'm falling back to tagging now.
