### ISSUE TITLE
In citation markup language doesn't work

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-browser#196]
In Citation text the markup language doesn't work.

Here an example:
![image](https://user-images.githubusercontent.com/98519154/177299730-9b706fac-0961-4413-bb3d-573d32ec140f.png)

**Comment by m-mohr** [comment]
sci:citation doesn't support CommonMark: https://github.com/stac-extensions/scientific#item-properties-and-collection-fields
So you'd need to ask for support in the extension first (on the other hand, sci:citation is meant for the actual citation, not a link to it...). :-)

**Comment by m-mohr** [comment]
Yeah, I'm aware that some people use this field in a way that it is not intended to be used. Maybe we need to change something in the scientific extension to allow for a link with a specific rel type or so.
