### ISSUE TITLE
Improve Additional resources show

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-browser#197]
I see the following possible improvements in showing the Additional resources:

1. Make clear when a new resource starts -> either with a bullet list or a table highlighting different rows. 
In the following examples it is not clear where the next resource starts:
![image](https://user-images.githubusercontent.com/98519154/177302243-72da1a8d-8f36-41c3-b999-fcb3760d3f62.png)
![image](https://user-images.githubusercontent.com/98519154/177302315-a279f563-19cf-4bab-b628-66ca9f70a938.png)

2. Concerning the specific links of type "citation", "related", "successor-version" and "latest-version" I would delete the parenthesis and use **:** or something similar (e.g. Citation: link to citation) and would also keep the link only on the resource itself and not also on the label.

3. I would also uniform the "related" link to the others, making it start with a capital letter and calling it "Related resource" which sounds clearer than "related" itself.

How it looks now
![image](https://user-images.githubusercontent.com/98519154/177303410-1e7c8428-7472-43e9-91c2-b5f235dd7d66.png)

A proposal:
![image](https://user-images.githubusercontent.com/98519154/177304466-517c62ca-f4e9-4045-9fa5-f0e2f0fa4f73.png)

**Comment by m-mohr** [comment]
Thanks for the suggestions.

1. In the recent UX discussions, it was proposed to remove the bullet points. I added a dash now as I came across some lists that indeed greatly benefit from having a bullet point or similar. Any second thoughts @trevorlang ?
2. Yeah, using the double colon looks better. I can't easily change where the link starts though, so I may need to consider that later.
3. Yes, the fallback labels derived from the rel type should be formatted better now.

How do you like it now? @chiarch84

**Comment by m-mohr** [comment]
I also implemented grouping, if necessary:

![grafik](https://user-images.githubusercontent.com/8262166/177319086-215b0713-c4aa-4f95-8159-7b432cba29e2.png)

**Comment by chiarch84** [comment]
Thanks a lot! It looks much better now! How do I set up grouping?

**Comment by m-mohr** [comment]
Grouping was not available yet, I just submitted the changes. They should be live in a minute. 
It basically just checks whether for a relation type there are >= 2 links and then switches from a plain list to grouping.

**Comment by chiarch84** [comment]
I tested it and it looks much better. I would though change the group title "Related resource" to plural "Related resources" since it includes more links. Thanks!!!

**Comment by chiarch84** [comment]
Ok, fine than! No problem!
