### ISSUE TITLE
When an element shows "read more" in the description when going to parent version it still appears

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-browser#198]
When an element shows "read more" in the description (when it is too long) when going to parent version through the "Go to Parent" button, the "read more" still appears even if the description is very short.

Here an example:
![image](https://user-images.githubusercontent.com/98519154/177320022-6e0929ef-9fa8-4cd5-b9bb-bf2fd73e31ae.png)

**Comment by m-mohr** [comment]
Interesting phenomena. I'll investigate...

**Comment by m-mohr** [comment]
Hmm, I've issued a potential fix, but I'm not sure whether it works always. Can you check whether it also works for you, @chiarch84 ?
