### ISSUE TITLE
Basic search text functionality for collections

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-browser#199]
I know that Collections search APIs have still not been defined, but I believe that the actual catalogue really misses a text search function for the collections. 

In our case for example we have more than 400 collections and it is impossible for the user to browse all of them to find the one he's looking for.  Most of the times though he would know the name of the collection he's looking for, or some important keywords.

A basic simple text search would be very helpful. Even if it is just a Js search function for identical strings in all collections fields it would already be better than nothing while waiting for the APIs to be defined and to come out with a specific search function.

**Comment by m-mohr** [comment]
Yes, I agree. It is only possible if the collections are not paginated though.

**Comment by chiarch84** [comment]
Sure, but do we have pagination now? I don't see it appearing anywhere

**Comment by m-mohr** [comment]
If the back-end sends next/prev links for collections, the browser does some kind of infinite scroll behavior. I'm just saying here that if this is the case for the API, a search is not very useful as it only filters what has been loaded already and not everything. So in this case the user doesn't show the option to not confuse users. But that's the same for sorting already.

**Comment by chiarch84** [comment]
The point is that I would want to search over all the collections of the catalog, not only the ones appearing in the home page.

In our case for example we've got the home page which has 22 catalogs that group together similar collections. I would want a search button that looks for all collections in the tree, not only the ones available in the same page which is already open.

Here a screenshot of our catalog now:

![image](https://user-images.githubusercontent.com/98519154/177324574-1201bccb-7b34-4c54-8763-d06b30fbc6fc.png)

In each catalog there are either collections or other sub-catalogs with other collections. 

Is all the tree loaded in memory from the beginning or not?

**Comment by m-mohr** [comment]
No, it is not in memory. This needs API support first. The only thing I can do right now is to filter what is shown.

**Comment by chiarch84** [comment]
Well, better than nothing. At least in the lists where I've got more than 20 collections I would directly find the one I'm looking for. It would already be a great improvement!

**Comment by m-mohr** [comment]
Basic search functionality is now present. It searches in id, title and keywords and is limited to the data that has already been loaded, which may only be what is shown already.

![grafik](https://user-images.githubusercontent.com/8262166/177328461-86a24571-bc1c-406b-9e10-52fbca1039ef.png)

**Comment by chiarch84** [comment]
It is already a great improvement! Thanks for the quickness of realization!

Some small suggestions:

- In the search field I would write "Search collections" rather than "search catalogs".
- I would also hide the search function when there is no collection in the list. In our home for example we have only catalogs, but the search function appears anyway.
- Finally I would probably search in the description field too.

Thanks again

**Comment by m-mohr** [comment]
> For point 2 I differentiated since I saw that the search was only working for collections and not for catalogs. I tried the search in my home page where I only have catalogs and the search doesn't return anything. (even with the correct search text of course)

I can't reproduce this without more context, but I assume the catalogs have not been loaded to memory yet. That was the drawback that I mentioned above:

>  It searches in id, title and keywords and is limited to the data that has already been loaded, which may only be what is shown already.



> For point 3 it's always a hard balance. I always compare it with my Elasticsearch index where I have all my collections (similar to the one used in fast-stac-apis). In the index the title and the description are indexed as 'text' which means that if I do a plain search I would find everything written also in the field "description". Anyhow this basic search won't be perfect since it is not a real API search, but I think that if you search also in the description and highlight in the shown resources the searched word, than it would be clearer in which resources you found that word.

Highlighting the words is not an easy task as you need to be aware of HTML etc. So I'm not digging down that rabbit hole, but I'm happy to accept PRs. Also, there might still not be a highlight as (1) the part of the description might not be shown or (2) the keywords are never shown.

**Comment by m-mohr** [comment]
Thanks for checking it again. I've also checked it again and I actually see an issue on my side as well. I've fixed it, but please check again whether it also works for you.

On the other hand, the search is pretty unreliable and I'm wondering whether it's worth having it?

Right now it works like that:
- If catalog/collection has been loaded, check id, keywords or title for the search terms
- If catalog/collection has not been loaded yet, check the href or title of the link for the search terms

That means you need to have good title in the links, otherwise search will likely not be very useful for catalogs and collections that are note directly delivered with metadata by a request to /collections.

**Comment by chiarch84** [comment]
Just retried and it works.

Well in our case it is much better to have it since we always need to look for resources in a list of 25 or more and I always end up searching with the browser search function. And also the users are complaining about it.

For what concerns the loading of the results I cannot really reproduce a case where they are not loaded. I organized our catalog so that it doesn't exceed 100 resources par catalog and in all those cases I don't have problems with the search function.

**Comment by m-mohr** [comment]
Okay, I'll leave it in for now and see what feedback we get in the beta phase.

**Comment by chiarch84** [comment]
In effect now this is solved, but another error appears after the change.

My items result empty:
![image](https://user-images.githubusercontent.com/98519154/177354905-40cd85d7-4d26-40e0-a600-f71161403987.png)

**Comment by m-mohr** [comment]
Ouch, sorry about that. I should have tested this a bit more. Fixed.

**Comment by chiarch84** [comment]
ok tested and now everything works! Thanks!
