### ISSUE TITLE
Broken child catalog links with prefixed root catalog URLs

### ISSUE THREAD

**Issue by duckontheweb** [radiantearth/stac-browser#203]
**STAC Browser Version:** `v3.0.0-beta.1`

**Steps to Reproduce:**

- Start STAC Browser pointing to Microsoft PC STAC API
   ```console
   $ npm start -- --open --catalogUrl https://planetarycomputer.microsoft.com/api/stac/v1
   ```
- Click on any child catalog card (use the "Dayment Annual Puerto Rico" collection for this example)
- Shows error stating that the resource could not be loaded. *Note that the "Requested URL" incorrectly has the `/v1` prefix repeated.
   <img width="1502" alt="Screen Shot 2022-07-13 at 9 46 14 AM" src="https://user-images.githubusercontent.com/6878073/178787819-45650d1e-4347-4cfd-86e6-6116205c52cb.png">

I can verify that the child link HREF is correct in the STAC catalog itself:

```console
$ curl https://planetarycomputer.microsoft.com/api/stac/v1 -s | jq ".links[] | select((.title != null) and (.title == \"Daymet Annual Puerto Rico\")) | .href"
"https://planetarycomputer.microsoft.com/api/stac/v1/collections/daymet-annual-pr"
```

Sorry, my Vue.js experience is limited so I wasn't able to track down the source of the issue.

**Comment by m-mohr** [comment]
Hey @duckontheweb,

you need to add a slash at the end of the URL as otherwise the Browser thinks that it's a file.

This is also documented in the Readme for the catalogUrl option:

> The URL of the catalog to show by default. If you don't point to a specific file make sure to append a / at the end of the URL!

**Comment by duckontheweb** [comment]
Right, sorry I missed that!
