### ISSUE TITLE
NavigationDuplicated error in console

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#207]
At least in the dev environment, the new app state functionality seems to give an error when expanding/collapsing a box:

For example:
`Routing Error NavigationDuplicated: Avoided redundant navigation to current location: "/collections%2Fsen12floods_s1_labels%2Fitems%2Fsen12floods_s1_labels_33_2019_05_17?.asset=asset-labels".`

No such error should be shown.

**Comment by rowanwins** [comment]
Having trouble replicating in the dev branch sorry @m-mohr , can you provide more specific reproduction steps?

**Comment by m-mohr** [comment]
Yeah, it seems not too easy to reproduce, but here's a step-by-step guide. It seems to only occur when private query parameters are used.

1. Go to e.g. `https://radiantearth.github.io/stac-browser/#/external/planetarycomputer.microsoft.com/api/stac/v1/collections/naip?~key=123`. It includes a random private key as I can't post a real token, but it doesn't matter here.
2. Open Dev Console in Browser
3. Click first item
4. Expand an asset
5. Error appears. It's easy to mute in StacBrowser.vue:273, but I'm not sure if that's really a good idea?

**Comment by rowanwins** [comment]
Still can't replicate sorry.
It seems like adding `~key=123` and hitting enter converts the url to `https://radiantearth.github.io/stac-browser/#/external/planetarycomputer.microsoft.com%2Fapi%2Fstac%2Fv1%2Fcollections%2Fnaip`
 and drops the key param?

**Comment by m-mohr** [comment]
Hmm, I can reliably reproduce this on multiple Windows computers with Chrome and Firefox. Is this maybe browser or OS dependant?

The behavior you are describing is correct. It is expected to drop the key param, I'm not sure about the URL encoding but on the other hand it also shouldn't hurt...

**Comment by m-mohr** [comment]
Reading a bit into it, I think we can safely mute this error as described here: https://stackoverflow.com/a/65879787
