### ISSUE TITLE
UI: Support for sending arbitrary headers or query parameters with requests

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-browser#210]
It would be nice to be able to specify arbitrary headers or query parameters with each request. This would support providing authentication credentials, for example, via an `Authorization: Bearer token` header or via a custom parameter (e.g., auth_token).

**Comment by m-mohr** [comment]
Where do you want to specify them?
You can already specify Headers and query parameters in the config of the Browser ( https://github.com/radiantearth/stac-browser/tree/dev#requestheaders ) and additionally, you can also pass through query parameters via URL ( https://github.com/radiantearth/stac-browser/tree/dev#private-query-parameters ).

**Comment by philvarner** [comment]
> Where do you want to specify them? UI? Config? URL? You can already specify Headers and query parameters in the config file of STAC Browser ( https://github.com/radiantearth/stac-browser/tree/dev#requestheaders - be aware, after deployment it's basically public ) 

UI, so they're not public. 

> additionally, you can also pass through query parameters via URL ( https://github.com/radiantearth/stac-browser/tree/dev#private-query-parameters ).

ah, this is what I'm looking for

**Comment by m-mohr** [comment]
Handling this via UI is a bit difficult in a user-friendly way, but it's on the roadmap. :-)

**Comment by m-mohr** [comment]
@philvarner There's now also a way to configure a basic UI for Auth: https://github.com/radiantearth/stac-browser/tree/dev#authconfig

**Comment by m-mohr** [comment]
For example the following config option enables the auth UI for Radiant MLHub:

![grafik](https://user-images.githubusercontent.com/8262166/183944934-82ea5e18-86c9-4b8e-a1cd-133552bf9439.png)


```js
module.exports = {
    catalogUrl: 'https://api.radiant.earth/mlhub/v1/', // Must have a slash at the end for folders/APIs
    authConfig: {
        type: 'query', // null or 'query' or 'header'
        key: 'key',
        description: `Please get the API key from your [Radiant MLHub Profile](https://mlhub.earth/profile).`
    }
    ...
};
```
