### ISSUE TITLE
authConfig doesn't seem to work

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-browser#221]
I configured in my config.js

```
authConfig:
        {
           type: 'query',
           key: 'auth_token'
        }
```

When I open stac-browser, I get the prompt to input the value for to be used for the query param, but the the UI just displays a spinner and no request goes out.  I saw the same thing with the "header" authConfig type.

**Comment by m-mohr** [comment]
Hey,
could you provide a bit more details and ideally a repro? The catalogs that I have access to only limit access to some parts, but maybe it doesn't work when the whole catalog requires auth...

**Comment by m-mohr** [comment]
I'm able to reproduce it, will work on a bugfix.

**Comment by m-mohr** [comment]
I've commited a bugfix, please let me know whether it works for you or not. :-)

**Comment by philvarner** [comment]
Works! thanks!
