### ISSUE TITLE
Better distinguish between errors accessing remote items

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-browser#224]
It looks like any error either retrieving or validating an item results in the same UI error, which states that this is typically a CORS issue. 

I just had a case where I was accessing an Item json that had a typo in it, and therefore wasn't valid. 

This code:            
```
if (!Utils.isObject(response.data)) {
              throw new Error('The response is not a valid STAC JSON');
            }
```
threw an exception, but the UI gave me the indication it was a CORS issue. 

It would be nice to have more precise errors when the items aren't valid.

**Comment by m-mohr** [comment]
Good point, I'll try to improve this.

**Comment by m-mohr** [comment]
The "The response is not a valid STAC JSON" error is now properly passed through.
