### ISSUE TITLE
Feature: Support for Query Extension and Filter Extension

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-browser#225]
Support for the query extension and filter extension would be great. As an MVP, just a text box that you can put the JSON (for either) or text (for CQL-Text) in would be useful.

This would only be shown if the API advertises those extensions in the conformance.

**Comment by m-mohr** [comment]
The filter extension is already implemented (for GET), but it requires correct conformance classes and a queryables endpoint. If you have that, you can use queryables for global Item search or on the Features Items endpoint.

The query extension is currently not planned to be implemented as it doesn't offer a way to get the queryables.

**Comment by philvarner** [comment]
You don't want to even support a text box for the Query extension body?

**Comment by m-mohr** [comment]
At least not by default. I feel like for most users it would be more confusing than having a text box where you can add cryptic query parameters. For this to be useful, users would need to read/know the Query Extension specification.

I'd accept a PR that adds such functionality if it could be enabled via config option and is disabled by default.
