### ISSUE TITLE
Setting useTileLayerAsFallback building option to false has no effect

### ISSUE THREAD

**Issue by jfbourgon** [radiantearth/stac-browser#227]
In order to overcome the issue about GeoTransform mentioned in #222, our local setup is built with both `tileSourceTemplate` and `useTileLayerAsFallback` options set. However this has no issue on the map renderer behavior since the `useTileLayerAsFallback` setting is ignored.

The issue seems related to the fact the value set as a building option through a command such as `npm run build -- --useTileLayerAsFallback=false ...` is interpreted/stored as a string in the resulting javascript file, thus never evaluated to `false`

See below for a snippet of the resulting file:
```
const Pt = Object.assign(vt, {
	report: !0,
	useTileLayerAsFallback: "false",
	pathPrefix: "/stac-browser/",
	catalogUrl: "https://my.own.stacapi.com/api/",
	tileSourceTemplate: "https://my.own.titiler.com/cog/tiles/{z}/{x}/{y}?url={url}"
})
```
manually fixing the resulting javascript file this way is sufficient to solve the issue and have our own Tiler service used for the COG asset rendering.
```
const Pt = Object.assign(vt, {
	report: !0,
	useTileLayerAsFallback: false,
	pathPrefix: "/stac-browser/",
	catalogUrl: "https://my.own.stacapi.com/api/",
	tileSourceTemplate: "https://my.own.titiler.com/cog/tiles/{z}/{x}/{y}?url={url}"
})
```

**Comment by m-mohr** [comment]
Thanks for the report. To clarify: You are using the config option and set it to boolean false and that does not work? Or are you using the CLI option and that doesn't work?

**Comment by jfbourgon** [comment]
I'm using the CLI option on the `npm run build` command.

**Comment by m-mohr** [comment]
Thanks, I've committed a fix.

(I was only able to test that it arrives correctly in the build file as my train is about to arrive, but I think it should work. Please let me know if you still have issues.)

**Comment by jfbourgon** [comment]
Also confirm that the proposed fix is addressing the issue on my end too The javascript file now contains the following config and the viewer is using a Tile Service by default once deployed.
```
const Pt = Object.assign(vt, {
	report: !0,
	useTileLayerAsFallback: !1,
	pathPrefix: "/stac-browser/",
	catalogUrl: "https://my.own.stacapi.com/api/",
	tileSourceTemplate: "https://my.own.titiler.com/cog/tiles/{z}/{x}/{y}?url={url}"
});
```
Thanks for the quick fix!
