### ISSUE TITLE
Add docker container for 3.0

### ISSUE THREAD

**Issue by geospatial-jeff** [radiantearth/stac-browser#230]
I think it would be really nice to have a `Dockerfile` in this repo.  This would make it easy to package the browser alongside API implementations (ex. docker-compose).

If we don't want to add a Dockerfile here, I would appreciate some guidance on how to build vue apps inside a Docker container so I may include it in stac-fastapi.

**Comment by geospatial-jeff** [comment]
I came up with this based on the stac-fastapi docker images.  It "works" but uses a python base image (lol) so probably not the best solution.

```dockerfile
FROM python:3.8-slim as base

ARG catalog_url

# Download dependencies
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y build-essential git curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install nodejs

# Download stac-browser
WORKDIR /app
RUN git clone https://github.com/radiantearth/stac-browser.git
WORKDIR /app/stac-browser
RUN git checkout v3.0.0-beta.3

# Install it
RUN npm install
```

You can then pass `npm start -- --open --catalogUrl=http://0.0.0.0:8082` as the container command.

**Comment by waystilos** [comment]
@m-mohr Can I take this task?
