### ISSUE TITLE
Browse hierarchy not always working

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-browser#231]
In a Catalgoue made of Sub-catalgoues, the browse side bar doesn't load correctly. 

Apparently the children of the sub-catalogues are not retrieved.

![image](https://user-images.githubusercontent.com/98519154/194557631-79d772d1-497d-46bc-bdf8-9c94da5ee794.png)

Here an example:
https://radiantearth.github.io/stac-browser/#/external/earth-search.aws.element84.com/v0/

**Comment by m-mohr** [comment]
Actually, these are collections and the items don't show up. Sometimes they do, it seems that some kind of race condition applies. I have to investigate further. Thanks for reporting the issue.

**Comment by chiarch84** [comment]
you are right @m-mohr in the example those one are collections and not sub catalogs. I hadn't seen it. In our case though we have sub-catalogs and it gives the same problem. The tree structure is correctly browsable in the main GUI but not in the Browser tab. In our case we see only catalog and relative sub-catalogs but when we try to open the children collections of a sub-catalog it says no children available.

**Comment by m-mohr** [comment]
I've committed a bug fix, which works for Earth Search. I hope this also solves your issues, but if not I'd need a reproducible example.

**Comment by chiarch84** [comment]
I just tried it with Catalogues and sub catalogues and it works fine! Thanks!

**Comment by chiarch84** [comment]
I would like to reopen this issue since I'm having some random problems with the rendering of the items in the Browse menu.

It happens very often that while clicking here and there for opening various collections, some of these ones don't show any item even if they do have items and even if the relative call is correctly performed.

Here follows a screenshot of a collection not rendering items and in the Dev Console the relative call correctly answered.
![image](https://user-images.githubusercontent.com/98519154/204476701-7c823266-0d46-4fe3-9db8-f1c7df4e88a3.png)

But then if I try again next time, the problem will arise for other collections randomly and not for this one.
![image](https://user-images.githubusercontent.com/98519154/204477264-5504f6bc-be26-49b3-9f48-ced0974e3d94.png)

**Comment by m-mohr** [comment]
Yes, I can reproduce this here: http://localhost:8080/external/explorer.digitalearth.africa/stac/
When opening the sidebar quickly for the first time the children often don't show up. If I close and re-open the sidebar, it works. I've checked the internal state a bit and it's an issue with how STAC Browser handles the STAC instances internally in the database, basically it creates two instances for the same thing and then the update procedure/listener is not attached correctly.

Unfortunately, this is a bit more work and I don't have any funding for STAC Browser work right now so this will likely not be fixed until someone funds the work or submits the PR, sorry.

**Comment by chiarch84** [comment]
Ok, no problem. Let's keep there then for the future. Thanks!

**Comment by m-mohr** [comment]
@chiarch84 This should be fixed in the latest dev version. It's more a workaround, but in my tests it worked. Can you verify whether it also works for you?

Refactoring the database has been moved to another issue #275.

**Comment by chiarch84** [comment]
sure I can test! I'll let you know if it works!
