### ISSUE TITLE
Running / building 3.0

### ISSUE THREAD

**Issue by waystilos** [radiantearth/stac-browser#232]
I hope it's okay to post question  about stac-browser-ramp on here. Sorry if it's not.

## Running Locally
When running locally, I'm trying to get this working:

`npm start -- --open --catalogUrl="https://planetarycomputer.microsoft.com/api/stac/v1/" --allowExternalAccess=true`

When I visit `http://0.0.0.0:8081/#/`, I don't see the catalog showing on the home page but the source is:

<img width="798" alt="image" src="https://user-images.githubusercontent.com/5862314/194678003-b24dd259-6b65-498f-85c7-48f3b7e13f97.png">

Is the correct way just to visit the catalog externally like: `http://0.0.0.0:8081/#/external/planetarycomputer.microsoft.com/api/stac/v1`?

## Building
Same question with build. When I run `npm run build -- --catalogUrl="https://test-api-management-stac.azure-api.net/api/" --allowExternalAccess=true`

When I run `serve -s dist`, I see a blank page and don't know how to see the catalogs. Any guidance is appreciated. Thank you!

**Comment by m-mohr** [comment]
Why are you using stac-browser-ramp? It's a customized version for a specific version. Please try again with this repository and the dev branch.

**Comment by waystilos** [comment]
> Why are you using stac-browser-ramp? It's a customized version for a specific host. Please try again with this repository and the dev branch.

I wanted to try out the new version of the STAC browser and didn't know it was on this dev branch. Thanks for letting me know. I really appreciate it.

**Comment by m-mohr** [comment]
I'll make this more clear in the Readme, thanks.
