### ISSUE TITLE
How to properly set up Tile proxy url

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-browser#239]
I tried to read the documentation but didn't clearly understand how to configure the Tile poxy url.
In my case the url would include the STAC ID of the item is there a specific variable with this value? 
Am I supposed to return a tile for each asset or can I just return one for each item? 
Thanks

**Comment by m-mohr** [comment]
STAC Browser v3 doesn't have a tile proxy setting any more, what you probably need is buildTileUrlTemplate: https://github.com/radiantearth/stac-browser/tree/dev#buildtileurltemplate - right?

**Comment by chiarch84** [comment]
Dear @m-mohr yes I believe this is the correct place where to look, but from the documentation it is not clear to me where I should use and place this buildTileUrlTemplate.

In my case it would be something like:
```
const layer = await stacLayer(data, {
  tileUrlTemplate: "https://tileurl?x={x}&y={y}&z={z}&assethref={url}",
  useTileLayerAsFallback: true
});
```

But it is not clear where I should write this constant to make it work in the STAC browser.

**Comment by m-mohr** [comment]
You can add it in the config file, e.g.

`buildTileUrlTemplate: ({href, asset}) => 'https://tileurl?x={x}&y={y}&z={z}&assethref=' + encodeURIComponent(asset.href.startsWith('/vsi') ? asset.href : href),`

**Comment by m-mohr** [comment]
You can add it in the config file, e.g.

`buildTileUrlTemplate: ({href, asset}) => 'https://tileurl?x={x}&y={y}&z={z}&assethref=' + encodeURIComponent(asset.href.startsWith('/vsi') ? asset.href : href),`

**Comment by m-mohr** [comment]
According to the stac-layer documentation that should work.  But looking at the code, there might be a bug in stac-layey and instead of the item it may return the asset as item. Could you verify that?

**Comment by m-mohr** [comment]
Once confirmed, this would be this PR that probably fixes it: https://github.com/stac-utils/stac-layer/pull/52

**Comment by chiarch84** [comment]
Thanks a lot for your help! I will try it and let you know. It won't be super soon  though since we're still setting up the tile server so can't really test the output for now.
