### ISSUE TITLE
screenshot / demo site?

### ISSUE THREAD

**Issue by rabernat** [radiantearth/stac-browser#24]
I am new to STAC and trying to learn more about the tools available. This looks like a very cool project! Thanks to all the contributors to stac-browser for your open-source efforts.

I am curious if there is a demo site somewhere or even a screenshot that shows what the catalog browser actually looks like.

**Comment by scottyhq** [comment]
hey @rabernat check out this page for up-to-date 'browsable' catalogs
https://github.com/radiantearth/stac-spec/blob/master/implementations.md

**Comment by mojodna** [comment]
https://planet-stac.netlify.com/ is the only one that I'm responsible for that's running the current version of the code.

**Comment by mojodna** [comment]
There are now multiple catalog browsers running current versions:

* [Google Earth Engine](https://gee.stac.cloud/)
* [Sentinel](https://sentinel.stac.cloud/)
* [Landsat](https://landsat.stac.cloud/)
* [Planet](https://planet.stac.cloud/)
* [CBERS](https://cbers.stac.cloud/)
* [SpaceNet](https://spacenet.stac.cloud/)
* [OpenEO](https://openeo.stac.cloud/)
* [sat-api](https://sat-api.stac.cloud/)
