### ISSUE TITLE
User-initiated authentication token entry

### ISSUE THREAD

**Issue by greyskyy** [radiantearth/stac-browser#243]
Currently the experimental `authConfig` option provides the ability to prompt users for an authentication token if a request fails.  However, this does not cover the case where the stac-server filters assets based on a valid login.  For example, unauthenticated users can view thumbnail images, while authenticated users receive the full list of assets in the stac item.

In this case, stac-browser will never prompt for authentication, since the http request returns successfully.

It would be ideal to have a way for users to trigger the authentication prompt, thus enabling them to enter authentication token information even when the stac-api doesn't return 401 errors.

**Comment by m-mohr** [comment]
Great idea! So when authConfig is defined I could simply add something like a login button at the top of the page, right?

**Comment by greyskyy** [comment]
@m-mohr Your proposed solution is exactly what I was thinking.

However, I'm not sure the implementation in the latest `dev` branch is correctly working.  After clicking the `Authenticate` button, I enter my token and then push `Submit`. At this point i'm stuck in a loop where the modal always pops up again and never clears unless I press `cancel`.

**Comment by m-mohr** [comment]
I've tested against the Radiant Earth API where it worked. Do you have something I can test with? Otherwise, I can't work on it...

**Comment by greyskyy** [comment]
> 

Let me look into this ... i have one but it's private... i'll check around.  I think the actual issue is #245 .  

I was wondering if the `setAuth` function ends up called twice.  Once when we submit on the auth window, and then again when requests are being made.  Since before it looked like the auth was only processed at a 401 error. Maybe something is called twice?  I'm really not that familiar with Vue though, so it's possible i'm getting things tangled in my head. 🤷‍♂️

**Comment by m-mohr** [comment]
Yes, I also just thought #245 might be the issue for the repetitive dialog popping up. Let's wait until I've fixed #245 and then try again. I'll also check how I can provide a more meaningful message if an error status code returns from the server.

**Comment by m-mohr** [comment]
#245 should be fixed, but after fixing it I think the issue could also be parallel requests that spawn the modal multiple times. Could you check again @greyskyy? If #245 doesn't help I'd need something to reproduce the behavior and them I'm happy to fix it.

**Comment by greyskyy** [comment]
> 

@m-mohr this looks to be fixed!  My tests show this working. #245 does seem resolved, which should also resolve this enhancement, too.  Thanks again.

**Comment by m-mohr** [comment]
Oh, great to hear, thanks for the update.
