### ISSUE TITLE
Authentication double-formats bearer tokens

### ISSUE THREAD

**Issue by greyskyy** [radiantearth/stac-browser#245]
With the resolution of https://github.com/radiantearth/stac-browser/issues/243 (thanks @m-mohr !!!), I repeatedly get 401 errors from the STAC api.  Investigation reveals that the "Bearer" prefix to the `authorization` format string is prepended twice.  I was able to get around this, by setting my `authConfig` as follows:

```javascript
{
    authConfig: {
        type: 'header',
        key: 'Authorization',
        formatter: token => token.startsWith("Bearer") ? token : `Bearer ${token}`,
        description: `Please retrieve the token from our [API console](https://example.com/api-console).`
    }
}
```

But, this feels like a work-around.  Likely the `authConfig.formatter` is called twice, but i couldn't trace it down.

**Comment by m-mohr** [comment]
Thanks, I'll have a look!

**Comment by m-mohr** [comment]
Could you also provide the original config without the workaround, please?

**Comment by greyskyy** [comment]
> Could you also provide the original config without the workaround, please?

The original was just copied from the docs.

```javascript
{
    authConfig: {
        type: 'header',
        key: 'Authorization',
        formatter: token => `Bearer ${token}`,
        description: `Please retrieve the token from our [API console](https://example.com/api-console).`
    }
}
```

**Comment by m-mohr** [comment]
Thanks, should be fixed. Please let me know if it doesn't work for you.
