### ISSUE TITLE
limit doesn't work when filters are active

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#251]
> Note for self - there are some APIs that don't use the `token` param, for example [this one](https://eovoc.spacebel.be/collections/datasets/items?limit=12&startRecord=13) uses `startRecord`, so probably need to work out how to make the handling more generic.

I have a STAC API with  Next and  Previous  `page` functionality for navigating the results of `..collections/<collection_id>/items`. 

GET Request example for filtering items of a collection:  

`..collections/<collection_id>/items?limit=12&page=13`

GET Request example for searching: 

 `..search?limit=12&page=13`

I dont use the PaginationExtension (not sure how to) but I have some custom code to deal with pagination and creation of links. The problem is that Pagination fails when the items are filtered/searched.  

**EXAMPLE:** 
![image](https://user-images.githubusercontent.com/16292338/212722155-f0d75592-8df6-4809-b572-23ff89e536c3.png)

The items get filtered successfully in primis, but when `Next` is clicked the GET request defaults to `limit=12`.

I am not sure where to look so i post the question here. Can someone give me a hint?

_Originally posted by @iliion in https://github.com/radiantearth/stac-browser/issues/204#issuecomment-1384261786_

**Comment by m-mohr** [comment]
Should be fixed, please let me know if this works for you, too. @iliion

**Comment by iliion** [comment]
I confirm that it works now.  Thanks @m-mohr  :)
