### ISSUE TITLE
Leafmap integration for searching and visualizing geospatial datasets from custom STAC API

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-browser#258]
I'm posting this interesting news that could give an idea for integrating this powerful open source tool into the STAC Browser.

https://www.linkedin.com/posts/qiushengwu_leafmap-geospatial-stac-activity-7023744763694567424-46OR?utm_source=share&utm_medium=member_desktop

https://leafmap.org/

**Comment by m-mohr** [comment]
leafmap is a Python package and needs a server, STAC Browser is JavaScript on the client-side. I'm not sure how that could be combined...
