### ISSUE TITLE
Which branches to use for deployment

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-browser#260]
Dear @m-mohr could you please give me a hint to understand which branches I should use for deployment?

In the past months I've always been using dev, but should I use together also gh-pages and others or these ones substitute the dev one? Sorry but I couldn't really find documentation about this. In case there is just point it out to me and I'll read it by myself. Thanks!

**Comment by m-mohr** [comment]
Here's an overview over branches:

-  master: The latest stable version (right now v2.0)
- dev: The latest development version (right now v3.0.0, this is likely what you are looking for)
- dev2: This is a badly named branch for STAC Index integration
- gh-pages: This is just the demo, you won't want to use this.
- stac-index: The v2-based integration into STAC Index
- all other branches are feature-branches for v3.0.0 that will eventually be merged into dev (e.g. i18n for the translation effort).

**Comment by chiarch84** [comment]
Thanks a lot for the information. So If I want to deploy a new developed feature such as [this one](https://github.com/radiantearth/stac-browser/issues/253) will I find it in dev ? 
I saw you wrote in your comments that you were updating gh-pages.

**Comment by m-mohr** [comment]
Yes.
Updating gh-pages was an exception as GitHub had an outage and I had to do this manually a day later or so.
