### ISSUE TITLE
Pluggable interface to share or open assets/links/document with other services

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#262]
Add a pluggable interface to share or open assets/links with other services, e.g.
- open a XYZ with Felt / ArcGIS online
- open a WMTS(?) with ArcGIS online
- open a COPC in the COPC Viewer
- open GeoJSON on geojson.io / cogeo.xyz (although natively supported?)
- open COG on geotiff.io (although natively supported?)
- open flatgeobuf in flatgeobuf viewer(?)

By default (similar to the source component):
- show URL
- allow copy to clipboard (remove `file://` prefix? #144 | #306)
- open/download in browser(?)

This might be a good opportunity to also work on the related issue #247.

For links we may need a different visual presentation as the normal "bullet point list" is not ideal, I guess.

This can be inspired by a similar interface in the openEO Web Editor.

**Comment by chiarch84** [comment]
How would this work in case the file has a local path? Could it be possible to configure somehow where to open the application and from where it should take the file assuming it might not always be an http URL?

**Comment by m-mohr** [comment]
The interface will be pluggable so you can extend it to your needs. How file paths will be handled depends on the plugin then.

---

Currently, we can share with Twitter and via Email, instead https://madewithvuejs.com/vue-social-sharing may be a more extensive option.
