### ISSUE TITLE
Bug in the search form

### ISSUE THREAD

**Issue by iliion** [radiantearth/stac-browser#264]
This is probably a Bug related to this [feature](https://github.com/radiantearth/stac-browser/issues/253) and the strange behaviour  is caused after this [commit](https://github.com/radiantearth/stac-browser/commit/1c4a685e02bc609b521d49b2bf77a938704d0cb9).

---

### Explanation

In essence the above feature #253 will work only if the landing page (aka. the root catalog) contains the following link:
```
{
      "rel": "data",
      "type": "application/json",
      "href": <base_url_here> + "/collections",
      "method": "GET"
}
```

In case this link is not present then it is not possible to insert a collection manualy into the search form. Basically I insert a collection in the Collections text area and I press enter and then it appears in the Item IDs area (see screenshot).

![image](https://user-images.githubusercontent.com/16292338/216127786-2eb445a9-3e1f-4a1f-8cda-1c3851ef4974.png)
 
I think the aforementioned feature is very useful and I was wondering if its possible to decouple its functionality from the fact that we need to keep a "data" link in the root catalog.  

---

Note: _Related [issue](https://github.com/radiantearth/stac-browser/issues/263)_

**Comment by m-mohr** [comment]
Sure, that's a bug, I'll fix that. Thanks for reporting.

**Comment by m-mohr** [comment]
Please try again :-)

**Comment by iliion** [comment]
It is resolved. Thanks a lot @m-mohr

**Comment by iliion** [comment]
Hi @m-mohr .It is true that now a user can insert a collection but the `collections` argument in  the query string remains empty. I hadnt noticed it last night . 

ex.: `http://s-jrciprjeop150p.cidsn.jrc.it:20008/search?limit=12&collections=`

Debug screenshot:
![image](https://user-images.githubusercontent.com/16292338/216288335-35321acf-b313-40d3-9733-e5f53bce872b.png)

**Comment by m-mohr** [comment]
I didn't had an API at hand yesterday that didn't had collections so this was somewhat a "blind" bug fix, but found one now so was able to actually check what's going on and it's fixed now as far as I can tell (at least it works for EarthSearch).
