### ISSUE TITLE
Missing German translations

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#269]
The German translation is missing the following phrases, maybe someone can assist with translating them:
- Ascending Node Crossing time
- Azimuth Looks
- Aziumth Pixel Spacing
- Equivalent Number of Looks
- Full Width Half Max
- Noise Equivalent Intensity
- Off-Nadir Angle
- Range Looks
- Range Pixel Spacing
- Range Resolution
- Tile Matrix Set Links
- Tile Matrix Sets
- View Geometry
- Viewing Azimuth

**Comment by p1d1d1** [comment]
@m-mohr a colleague of mine will take care of it.

**Comment by davidoesch** [comment]
Assuming they are all covering remote sensing data.... especially Sentinel 1 Data as descriebd in https://ec.europa.eu/research/participants/portal4/doc/call/fp7/fp7-space-2012-1/31656-s1-rs-mda-52-7440product_definition_2_3_en.pdf 

To be honest: in DE those expression are mostyl not used - they do make more sense in EN

**Ascending Node Crossing time**

DE:  "Zeitpunkt am Äquator des aufsteigenden Knotens"

Die Ortszeit des aufsteigenden Knotens (Local Time of Ascending Node, LTAN) ist ein Begriff aus der Raumfahrt und bezieht sich auf den Zeitpunkt, zu dem ein Satellit die Ebene des Äquators in Richtung Norden kreuzt. Sie ist definiert als der Winkelabstand zwischen dem aufsteigenden Knoten (dem Punkt, an dem die Bahn des Satelliten den Äquator von Süden nach Norden kreuzt) und dem Frühlingspunkt, der durch den Schnittpunkt des Äquators mit der Ekliptik definiert ist.

Die LTAN wird normalerweise in Stunden und Minuten angegeben und bezieht sich auf eine bestimmte geografische Position auf der Erde. Sie ist definiert als die Zeit, zu der der aufsteigende Knoten eines Satelliten über den Meridian (die gedachte Linie, die den Nord- und Südpol verbindet) dieser Position kreuzt. Die LTAN hängt also von der Bahn des Satelliten und der geografischen Position des Beobachters ab.

Die "Ascending Node Crossing time" ist der Zeitpunkt, zu dem der Satellit die Ebene des Äquators in Richtung Norden kreuzt. Sie ist also direkt mit dem aufsteigenden Knoten verbunden und wird oft zusammen mit der LTAN angegeben.


**Azimuth Looks**

DE: "Anzahl der seitlichen Bildaufnahmen"

Der Begriff "Azimuth Looks" wird im Zusammenhang mit Fernerkundung und insbesondere bei der Auswertung von SAR Satellitenbildern verwendet. Er bezieht sich auf die Richtung, aus der ein Satellitenbild aufgenommen wurde.

In der deutschen Sprache gibt es keine direkte Entsprechung für den Begriff "Azimuth Looks". Man könnte den Begriff möglicherweise als "Azimutale Perspektive" oder "Azimutale Ansicht" übersetzen. Dabei bezieht sich "Azimut" auf den Winkel zwischen dem geografischen Nordpol und dem Standpunkt des Beobachters.

Alternativ könnte man auch den Begriff "Blickwinkel" verwenden, um die Perspektive zu beschreiben, aus der ein Satellitenbild aufgenommen wurde. Dies könnte jedoch je nach Kontext eine etwas andere Bedeutung haben.

Da hier der Begriff in der Mehrzahl verwendet wird , vermute ich das es um "number of azimuth looks" geht. "Number of Azimuth Looks" bezieht sich auf die Anzahl der verschiedenen oder überlappenden kohärent verarbeiteten "Looks", die aus dem Dopplerspektrum extrahiert werden und nach der Erkennung kombiniert werden, um das Bild zu bilden.

Ein "Look" ist ein Signal, das von einem Radarsensor ausgesendet wird, um ein Objekt oder eine Landschaft zu erfassen. Das Signal wird dann empfangen und verarbeitet, um Informationen über das Zielobjekt oder die Landschaft zu liefern.

Die "Number of Azimuth Looks" ist also die Anzahl der verschiedenen "Looks" in der seitlichen Richtung (Azimut), die von einem Radar ausgesendet und empfangen werden, um ein Satellitenbild zu erzeugen. Je mehr "Looks" verwendet werden, desto höher ist die Auflösung und Genauigkeit des resultierenden Bildes.

Auf Deutsch könnte man "Number of Azimuth Looks" als "Anzahl der Azimut-Looks" oder "Anzahl der seitlichen Radarbilder" übersetzen. Es handelt sich um einen Begriff aus der Radartechnik und der Fernerkundung.

**Azimuth Pixel Spacing**

DE: "Azimutaler Pixelabstand"

"Azimuth Pixel Spacing" bezieht sich auf den Abstand zwischen den einzelnen Pixeln in der seitlichen (Azimut-)Richtung eines Satellitenbildes.

Das Azimut-Pixel-Intervall wird durch die seitliche Auflösung des Radarsensors bestimmt, der das Bild aufgenommen hat, sowie durch den Winkelabstand zwischen den einzelnen "Looks", die zur Bildgebung verwendet wurden.

Ein kleinerer Azimut-Pixelabstand bedeutet eine höhere laterale Auflösung, da mehr Pixel in der seitlichen Richtung zur Verfügung stehen, um Details darzustellen. Der Azimut-Pixelabstand hängt auch von der Größe des abgebildeten Bereichs ab - ein größeres Gebiet erfordert normalerweise größere Pixelabstände, um das Bild in angemessener Zeit aufnehmen und verarbeiten zu können.

Auf Deutsch könnte man "Azimuth Pixel Spacing" als "Abstand zwischen den Azimut-Pixeln" oder "Azimutaler Pixelabstand" übersetzen. Es handelt sich um einen wichtigen Parameter in der Bildverarbeitung und der Fernerkundung.

**Equivalent Number of Looks**

DE: "Äquivalente Anzahl von Looks"

"Equivalent Number of Looks" (ENL) ist ein Begriff aus der Radarbildverarbeitung und bezieht sich auf die Anzahl der kohärent verarbeiteten "Looks", die erforderlich wären, um eine bestimmte Rauschunterdrückung zu erreichen, wenn nur eine einzige Aufnahme verwendet würde.

Die Rauschunterdrückung ist ein wichtiger Aspekt bei der Verarbeitung von Radarbildern, da das empfangene Signal aufgrund von Störungen und Rauschen verzerrt werden kann. Durch die Kombination von mehreren "Looks" kann das Signal verstärkt und das Rauschen reduziert werden.

Das ENL gibt an, wie viele kohärent verarbeitete "Looks" benötigt werden, um das gleiche Signal-Rausch-Verhältnis (SNR) zu erreichen wie bei der Verwendung einer einzelnen Aufnahme mit einer bestimmten Rauschunterdrückung.

Auf Deutsch könnte man "Equivalent Number of Looks" als "Äquivalente Anzahl von Looks" oder "Äquivalente Anzahl von Radarsignalen" übersetzen. Der Begriff ist wichtig für die Beurteilung der Qualität von Radarbildern und bei der Auswahl geeigneter Verarbeitungstechniken.

**Full Width Half Max**

DE "Halbwertsbreite des Signals"
In der Fernerkundung wird FWHM oft bei der Charakterisierung von Radarsignalen und der Radaraufnahmegeometrie verwendet.

Im Zusammenhang mit der Radarsignalverarbeitung bezieht sich FWHM auf die Breite des Signalpulses auf halber Höhe der maximalen Amplitude. Es gibt an, wie breit das Radarsignal ist und bestimmt damit die Auflösung des Radarsensors. Je schmaler die FWHM, desto höher ist in der Regel die Auflösung des Radarsensors.

Im Zusammenhang mit der Radaraufnahmegeometrie bezieht sich FWHM auf die Breite des Abtastbereichs (Footprints) des Radarsensors, wenn das Signal auf den Boden projiziert wird. Es gibt an, wie groß der Bereich ist, der von jedem einzelnen Abtastpunkt abgedeckt wird. Je schmaler die FWHM, desto höher ist in der Regel die laterale Auflösung des Radarsensors.

In beiden Fällen kann FWHM ein wichtiger Parameter sein, um die Qualität von Radarbildern und die Leistungsfähigkeit des Radarsensors zu bewerten. Auf Deutsch könnte man "Full Width Half Maximum" in diesem Zusammenhang als "Halbwertsbreite des Radarsignals" oder "Breite des Abtastbereichs" übersetzen.

**Noise Equivalent Intensity**

DE "Rauschäquivalente Intensität"

Noise Equivalent Intensity" (NEI) ist ein Begriff, der in der Radarbildverarbeitung verwendet wird, um das Rauschniveau in einem empfangenen Radarbild zu beschreiben.

NEI gibt an, welche Signalstärke erforderlich ist, um das gleiche Rauschniveau zu erreichen wie das Rauschniveau im Bild. Das Rauschniveau wird oft in Bezug auf die Hintergrundrauschtemperatur oder die Systemrauschzahl angegeben.

NEI wird häufig verwendet, um die Empfindlichkeit von Radarsensoren zu beschreiben. Ein Sensor mit einer niedrigeren NEI hat eine höhere Empfindlichkeit und kann schwächere Signale im Verhältnis zum Rauschen erkennen.

Auf Deutsch könnte man "Noise Equivalent Intensity" als "Rauschäquivalente Intensität" oder "Äquivalentes Rauschintensitätsniveau" übersetzen. Der Begriff ist wichtig für die Bewertung der Leistungsfähigkeit von Radarsensoren und für die Auswahl geeigneter Verarbeitungstechniken

**Off-Nadir Angle**

DE "Nebennadir- Winkel" 
gemäss https://www.fe-lexikon.info/lexikon-n.htm#nebennadir


**Range Looks**
DE: "Anzahl der Entfernungsabtastungen"

"Range Looks" ist ein Begriff in der Radartechnologie und bezieht sich auf die Anzahl der Messungen, die entlang der Range- oder Entfernungskomponente eines Radarsignals durchgeführt werden.

In der Fernerkundung wird das Signal entlang der Range-Richtung in aufeinanderfolgenden Impulsen abgetastet. Die Anzahl der Abtastungen pro Impuls wird als "Range Looks" bezeichnet. Die Anzahl der Range Looks bestimmt die laterale Auflösung des Radarsignals, die sich aus der Interferenz der einzelnen Abtastungen ergibt.

Eine höhere Anzahl von Range Looks führt zu einer höheren lateralen Auflösung, aber auch zu einer längeren Verarbeitungszeit und einer größeren Datengröße. Eine niedrigere Anzahl von Range Looks führt zu einer schnelleren Verarbeitung und einer kleineren Datengröße, aber auch zu einer niedrigeren lateralen Auflösung.

Auf Deutsch könnte man "Range Looks" als "Entfernungs-Abtastungen" oder "Reichweiten-Abtastungen" übersetzen. Der Begriff ist wichtig für die Charakterisierung von Radarbildern und die Auswahl geeigneter Verarbeitungstechniken.

Da bei Radarfernerkundung die Anzahl wichtig ist  "Anzahl der Entfernunsgabtastungen"

**Range Pixel Spacing**
DE "Pixel Abstand der Distanzmessung" ( I would stick here to the EN version

"Range Pixel Spacing" ist ein Begriff in der Radarbildverarbeitung und bezieht sich auf den Abstand zwischen den Abtastungen entlang der Range- oder Entfernungskomponente eines Radarsignals.

In der Radarbildverarbeitung wird das Signal entlang der Range-Richtung in aufeinanderfolgenden Impulsen abgetastet. Die Abstände zwischen den Abtastungen, die als "Range Pixel" bezeichnet werden, bestimmen die laterale Auflösung des Radarsignals.

Der Range Pixel Spacing wird üblicherweise in Metern oder anderen Einheiten der Entfernung gemessen und hängt von der Größe der Pulsbandbreite, der Sendeimpulsdauer und der Geschwindigkeit des Radarsignals ab.

Eine höhere laterale Auflösung erfordert in der Regel einen kleineren Range Pixel Spacing, was zu einer größeren Anzahl von Abtastungen und einer größeren Datenmenge führen kann. Eine niedrigere laterale Auflösung erfordert einen größeren Range Pixel Spacing, was zu einer geringeren Anzahl von Abtastungen und einer kleineren Datenmenge führen kann.

Auf Deutsch könnte man "Range Pixel Spacing" als "Abstand zwischen den Reichweiten-Pixeln" übersetzen. Der Begriff ist wichtig für die Charakterisierung von Radarbildern und die Auswahl geeigneter Verarbeitungstechniken.

**Range Resolution**
DE "Entfernungsauflösung"

"Range Resolution" ist ein Begriff aus der Radarbildverarbeitung und beschreibt die Fähigkeit eines Radarsystems, Objekte auf der Basis der Entfernung voneinander zu unterscheiden.

Die Range Resolution ist eng mit der Pulsbandbreite des Radarsignals verbunden und wird durch die Dauer des Sendeimpulses bestimmt. Je kürzer der Sendeimpuls, desto breiter ist die Pulsbandbreite und desto höher ist die Range Resolution.

Die Range Resolution wird üblicherweise in Metern oder anderen Einheiten der Entfernung gemessen und hängt auch von der Signalverarbeitung und der Rauschunterdrückung ab.

Eine höhere Range Resolution bedeutet eine höhere Fähigkeit zur Unterscheidung zwischen Objekten in der Entfernung, aber auch eine höhere Komplexität und Datengröße des Radarsystems. Eine niedrigere Range Resolution führt zu einer schnelleren Verarbeitung und einer geringeren Datengröße, aber auch zu einer niedrigeren Fähigkeit zur Unterscheidung zwischen Objekten in der Entfernung.

Auf Deutsch könnte man "Range Resolution" als "Reichweitenauflösung" oder "Entfernungsauflösung" übersetzen.

**Tile Matrix Set Links**
DE "Kachelmatrix-Set Links"

"Tile Matrix Set Links" (TMS-Links) sind ein Konzept in der Kartographie und Geoinformatik, das zur Organisation von Kacheln oder Tiles von Karten und räumlichen Daten verwendet wird. Siehe  

TMS-Links stellen einen standardisierten Weg dar, um auf eine bestimmte Kachel in einem Kachelset oder in einer Kachelmatrix zuzugreifen. Kacheln sind typischerweise rechteckige Ausschnitte von geographischen Daten wie Karten oder Luftbildern und werden häufig zur schnellen Anzeige von Karten in Webanwendungen verwendet.

Die TMS-Links bestehen aus einer URL-Struktur, die den Zugriff auf die Kacheln definiert. Die URL enthält Informationen wie die Zoomstufe, die Position der Kachel in der Kachelmatrix und den Dateinamen der Kachel. Durch die Verwendung von TMS-Links können Webanwendungen die benötigten Kacheln dynamisch und effizient laden, um ein schnelles und flüssiges Benutzererlebnis zu gewährleisten.

TMS-Links sind Teil einer Reihe von Technologien und Standards für die Verarbeitung, Speicherung und Übertragung von Geodaten in Webanwendungen und Geoinformationssystemen. Sie werden von einer Vielzahl von Anbietern und Entwicklern von Geodaten und Kartenanwendungen eingesetzt.

Eine direkte deutsche Übersetzung für den Begriff "Tile Matrix Set Links" wäre "Kachelmatrix-Set-Links".

**Tile Matrix Sets**
DE "Kachelmatrix-Set"

siehe https://docs.opengeospatial.org/is/17-083r2/17-083r2.html 
Ein TMS ist eine Sammlung von Kachelmatrizen, die in der Regel in verschiedenen Zoomstufen dargestellt werden. Jede Kachelmatrix besteht aus einer Rasteranordnung von Kacheln, die jeweils einen rechteckigen Ausschnitt der räumlichen Daten darstellen. Je höher die Zoomstufe ist, desto detaillierter sind die Kacheln und desto größer wird die Anzahl der Kacheln.

**View Geometry**
DE "Aufnahmegeometrie"
https://www.fe-lexikon.info/lexikon-r.htm#radarinterferometrie wird meist von Aufnahmegeometrie gesprochen


**Viewing Azimuth**
DE "Aufnahmeazimut"
Der Aufnahmeazimut bezieht sich auch auf den horizontalen Winkel, unter dem eine Kamera oder ein Sensor auf ein Gelände oder Objekt gerichtet ist, und wird normalerweise in Grad angegeben.

**Comment by m-mohr** [comment]
Vielen Dank, @davidoesch!
