### ISSUE TITLE
all text fields not being translated (into german), all are named the same: "Benötigt keine Übersetzung. Hier wird nur die formelle Übersetzung verwendet (de_DE)."

### ISSUE THREAD

**Issue by 01msmr** [radiantearth/stac-browser#271]
after installation of Nextcloud Desktop (version 3.7.2.13805) on macOS 13.2 (Ventura) with german as standard language, all menu elements of the App of Nextcloud Desktop are "overwritten" with this text:

`Benötigt keine Übersetzung. Hier wird nur die formelle Übersetzung verwendet (de_DE).`

… which means sth. like …

`No translation needed. Here just the formal translation is used (de_DE).`

<img width="497" alt="Bildschirm­foto 2023-02-09 um 20 32 53" src="https://user-images.githubusercontent.com/12639219/217919349-4eb743ff-d273-45d9-9cce-cd5860d0ce4a.png">

<img width="267" alt="Bildschirm­foto 2023-02-09 um 20 25 02" src="https://user-images.githubusercontent.com/12639219/217919533-b5c63aa0-846b-4b47-9227-c6708acac9d6.png">

**Comment by m-mohr** [comment]
Posted in the wrong repository.
