### ISSUE TITLE
Missing translation: "Snow/Ice Cover"

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#277]
A new phrase has been added for `eo:snow_cover` in stac-fields, we need new translations for "Snow/Ice Cover"

- [x] French @jfbourgon 
- [x] German @m-mohr 
- [x] Italian @p1d1d1 
- [ ] Romanian @rnanclares 
- [x] Spanish @mneagul 

You can just provide the translated phrase in a comment below. Thanks.

**Comment by jfbourgon** [comment]
Here is the suggested French translation:
`Couverture de neige et de glace`

**Comment by rnanclares** [comment]
Hi @m-mohr , proposed spanish translation:
`cobertura de nieve`

**Comment by m-mohr** [comment]
Thanks, added!

**Comment by p1d1d1** [comment]
Copertura nevosa/glaciale

**Comment by m-mohr** [comment]
For Romanian I've added "Acoperire cu zăpadă și gheață" for now, let me know whether that's correct. @rnanclares
