### ISSUE TITLE
Missing Romanian translations

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#278]
The following phrases are missing in Romanian:

- Search through the data offering of {title}.
- Nothing entered yet
- Digital Orthophoto Quarter Quadrangle
- Lightning Events
- Lightning Flashes
- Lightning Groups
- Lightning flash maximum time difference among lightning events in a flash
- Lightning group maximum time difference among lightning events in a group
- Time Threshold in a Flash
- Time Threshold in a Group

**Comment by mneagul** [comment]
I still have to clarify the "Lightning *" and "Digital Orthophoto *" stuff but in the next two days I will commit a version, hopefully final. I have to reach to the tech community for the proper translation.

**Comment by mneagul** [comment]
If no option is found then I will have to follow the way paved by the French and Italian translations.

**Comment by mneagul** [comment]
In fe2d2b6 I updated the translation. Also I removed some of the artefact from French that have been used as a base for translation

**Comment by mneagul** [comment]
@m-mohr I tried searching for references related to "Lightning Events" & Co in the source code and I'm not able to find the context. Do you have some pointers on how to find out the translation context ?

**Comment by m-mohr** [comment]
Thank you for the updates @mneagul!

> Also I just noticed that there are some more parts that are not translated, particularly from the S2 and S1 namespaces.

Yes, this is due to the fact that these fields are not specified in an extension or so and as such there will always be custom fields that are not covered by the translations and will not be shipped with STAC Browser by default. 

If you want to translate them in your fork or so, you can do so through the file with custom phrases (custom.json) in the respective language. Example:
```json
{
  "authConfig": {
    "description": ""
  },
  "fields": {
    "Mgrs Tile": "MGRS Kachel",
    "Water Percentage": "Wasser (Prozent)"
  }
}
```

I've added documentation for it here: https://github.com/radiantearth/stac-browser/tree/dev#custom-phrases

> I tried searching for references related to "Lightning Events" & Co in the source code and I'm not able to find the context. Do you have some pointers on how to find out the translation context ?

All phrases in the fields.json are not coming from STAC Browser, but from metadata fields that are defined in stac-fields.
STAC fields is responsible for generating the metadata rendering and the base for it is the fields.json file:
https://github.com/stac-utils/stac-fields/blob/main/fields.json#L661
It doesn't give you a lot of context, but you can see that the lightning phrases for example belong to the goes extension:
https://github.com/stac-extensions/goes#glm-only

Hope it helps, otherwise let me know.

**Comment by m-mohr** [comment]
New missing translation: "Nothing entered yet"

**Comment by m-mohr** [comment]
Closing in favor of our new Localization Management Tool: https://crowdin.com/project/stac-browser
