### ISSUE TITLE
Missing translation: "Nothing entered yet"

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#282]
A new phrase has been added, we need a new translation for "Nothing entered yet" (i.e. in the collection and item select box on the search form).

- [x] French @jfbourgon 
- [x] German @m-mohr 
- [x] Italian @p1d1d1 
- [ ] Romanian @mneagul  (=> #278)
- [x] Spanish @rnanclares

You can just provide the translated phrase in a comment below. Thanks.

**Comment by rnanclares** [comment]
Hi @m-mohr you got me mixed up, I'm the Spanish translator. I suppose @mneagul is the Romanian translator.

**Comment by m-mohr** [comment]
Yes, indeed, sorry for that. And thanks for the translation!

**Comment by p1d1d1** [comment]
"Nessun valore inserito"

**Comment by jfbourgon** [comment]
"Aucune information saisie"

**Comment by m-mohr** [comment]
Thanks all!
