### ISSUE TITLE
New translation for search

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#285]
A new phrase has been added:

> Search through the data offering of {title}.

- [x] French @jfbourgon 
- [x] German @m-mohr 
- [x] Italian @p1d1d1 
- [ ] Spanish @rnanclares (DeepL proposed "Buscar en la oferta de datos de {title}.")

You can just provide the translated phrase in a comment below. Thanks.

Sorry for the number of requests, in the future I'll try to request them in bulk before the releases. :-)

**Comment by p1d1d1** [comment]
Cerca tra i dati offerti da {title}.

**Comment by jfbourgon** [comment]
Rechercher parmi l'offre de données de {titre}.

**Comment by rnanclares** [comment]
Buscar en los datos ofrecidos por {title}
