### ISSUE TITLE
Search Interface for STAC API

### ISSUE THREAD

**Issue by mattfung** [radiantearth/stac-browser#30]
Hello,

I'm considering making a contribution and am wondering if there's interest for adding a search page on the browser that enables user to search items by collection name, time, and geometry? This would likely be a map display of items available along with a form on the side. Once an item is selected, the user will be redirected to the items page. As well, the search UI will likely work only with STAC API, and not with static catalogs.

Suggestions are welcome

**Comment by mojodna** [comment]
@scisco and others were working on something like this. I can't remember its name off the top of my head (stac-search?).

STAC Browser's primary constituency is the static catalog set, so this functionality may not be the best fit here (but if it's easy and would help you...).

**Comment by scisco** [comment]
Yeah, Development Seed made a search interface for STAC API: https://github.com/sat-utils/sat-api-browser

**Comment by m-mohr** [comment]
Filtering items in a specific collection has been implemented:

![grafik](https://user-images.githubusercontent.com/8262166/130359179-796b328b-933a-4108-b800-ce96020eecfb.png)

**Comment by m-mohr** [comment]
Cross-collection Item search has been implemented in STAC Browser v3.0.0-alpha.4. It's only core fields (excl. intersects) and no extensions yet, but it's a start. For extensions (e.g. sort, filter/CQL) please create separate issues if you are interested in the functionality.
