### ISSUE TITLE
Make it more obvious how to get the URL for a COG

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-browser#306]
When I see a COG in STAC Browser I only get the option to 'download':

<img width="777" alt="Screenshot 2023-04-19 at 8 56 39 PM" src="https://user-images.githubusercontent.com/407017/233254422-8b5555fa-ca11-491f-bcd0-b47dc8d4441c.png">

If I want to stream it (into cogeo.org/map, cogeo.xyz, qgis, etc) then I have to right click and 'copy link address'. It'd be nicer if there was a 'copy' option for the URL, making it clear you can use that to stream to other applications.

**Comment by m-mohr** [comment]
Yes, this will be solved as part of #262 ("allow copy to clipboard") :-)
