### ISSUE TITLE
Required spatio-temporal extent object format doesn't match current specification

### ISSUE THREAD

**Issue by rskelly** [radiantearth/stac-browser#31]
It looks like the current STAC spec requires that [spatial and temporal extents](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#spatial-extent-object) be formatted as an array-in-an-array (to support multiple bounding boxes in the future), while the browser seems to require a single array or it fails. The example datasets (e.g. [Planet Disaster](https://storage.googleapis.com/pdd-stac/disasters/catalog.json)) are formatted with a single array.

**Comment by lossyrob** [comment]
This has since been fixed, thanks!
