### ISSUE TITLE
GeoJSON show on map button isnt working

### ISSUE THREAD

**Issue by rockliffelewis** [radiantearth/stac-browser#312]
I have a bunch of GeoJSON assets on collections, and there's a nice helpful button next to them that says `Show on Map` that doesn't appear to do anything.

No errors in the console, and no fetch in the network traffic either

**Comment by m-mohr** [comment]
Can you provide a reproducible example, please?

**Comment by rockliffelewis** [comment]
Here you go:
https://data.aad.gov.au/stac-browser/external/transfer.data.aad.gov.au/aadc-aerial-photography/casc8916/collection.json?.language=en

**Comment by m-mohr** [comment]
Thanks, has been fixed.
