### ISSUE TITLE
Can't translate fields.json

### ISSUE THREAD

**Issue by gtitov** [radiantearth/stac-browser#316]
I followed [this instruction](https://github.com/radiantearth/stac-browser#adding-a-new-language). It works just fine for `texts.json`. But I couldn't manage to translate `fields.json`. My edits didn't show up if I edit `en/fields,json` directly also.

I found out that it happens because this line is commented out from `en/default.json` (and copied `en` folder to base the translation on it)

```js
// { fields: require('./fields.json') },
```

I'd suggest either making a remark in the docs or uncommenting the line to make locales consistent.

**Comment by m-mohr** [comment]
What are you trying to change? Add a new language? Edit an existing one?
I can't reproduce this without more information. Can you put up some example code, e.g. via a PR?

If you want to change things in fields. json for the en language, you indeed need to include the line above. By default it's not needed as the english keys and values are exactly the same and thus you can save some kb in transfer.

**Comment by m-mohr** [comment]
True, if you start with the English version this is misleading. I'll add a note to the contrib guide, thanks.

**Comment by m-mohr** [comment]
Fixed. I'd like to see your new translation as a PR so that we can grow the number of translations :-)
