### ISSUE TITLE
stac-browser using stac-server API; API link behavior

### ISSUE THREAD

**Issue by jlaura** [radiantearth/stac-browser#319]
I am wonder if this is something that I have misconfigured?

Here is an [example](https://stac.astrogeology.usgs.gov/browser-dev/#/collections/galileo_usgs_photogrammetrically_controlled_observations) of a collection served via stac-browser. The collection is contained within a catalog [here](https://stac.astrogeology.usgs.gov/api/). The API is titled and that title does not seem to be used in the navigation UI. Additionally, neither 'api' nor 'Up' is not resolving.

![Screen Shot 2023-05-11 at 12 01 40 PM](https://github.com/radiantearth/stac-browser/assets/2105468/3eb6a26d-01ba-4802-97c3-30a4661e498c)

This behavior is new in 3.0.0. Any thoughts?

**Comment by m-mohr** [comment]
Thanks for the report. The example doesn't load for me so it's hard to check the source file on potential issues. Can you link to the actual JSON file/response?

> Additionally, neither 'api' nor 'Up' is not resolving.

I assume this is not meant to contain the "not", right?

**Comment by jlaura** [comment]
@m-mohr Apologies it isn't loading! Is https://stac.astrogeology.usgs.gov/browser-dev/#/collections/galileo_usgs_photogrammetrically_controlled_observations accessible? One can see the behavior there.

Those links are dead and try to resolve to the URL in the screen shot below. I am not sure where the URL is being concatenated from. The `catalogURL` in the `config.js` is: `catalogUrl: "https://stac.astrogeology.usgs.gov/api/"`. So, the tail of that URL seems to be coming from the config. Not sure about the root (up to /collections).

<img width="765" alt="Screen Shot 2023-05-11 at 12 49 35 PM" src="https://github.com/radiantearth/stac-browser/assets/2105468/ba0e98e2-35c6-4a0e-a77f-f1d599f0d4db">

**Comment by m-mohr** [comment]
The main issue here is that the URL that the API reports is `https://stac.astrogeology.usgs.gov/api`, while the config sets `https://stac.astrogeology.usgs.gov/api/` as `catalogUrl`. From a URI perspective, the first URL is not equal to or a child of the second URL due to the missing slash at the end, so it assumes that the URLs are all "external".

So if I remove the trailing slash from the `catalogUrl`, it works as expected for me.

The config asks for the slash at the end as in most cases it (in most cases) avoids issues with relative URLs. For your case it looks like all your URLs are absolute though so you can use `https://stac.astrogeology.usgs.gov/api` and it should work.

**Comment by m-mohr** [comment]
I assume this solves the issue, so I'm closing, but please leave a comment if there's still an issue after changing the catalogUrl.

**Comment by jlaura** [comment]
@m-mohr That almost fixed it! I swapped the catalogURL as suggested, omitting the trailing slash. This gets the homepage loading as expected. I also realized that upstream IT must have put strict controls on mime-types, so I added the needed changes to the mime-types for `*.js` and `*.css` files. This means those links should now be working.

As deployed, this is still now adding `/api/api/` when attempting to navigate from the homepage to a catalog. I checked my cloudfront rules and am not seeing where that might be coming in from. Is it possible that rewrites with an added `api` are coming in from stac-browser? Since I can direct navigate to a catalog specific landing page, I do not think it is on the Cloudfront side.

Here is the now working URL for the homepage: https://stac.astrogeology.usgs.gov/browser-dev/#/?.language=en
The direct link to a catalog which is working: https://stac.astrogeology.usgs.gov/browser-dev/#/collections/galileo_usgs_photogrammetrically_controlled_observations?.language=en

When attempting to navigate from the homepage to that catalog (or any others), I am seeing:

<img width="1087" alt="Screen Shot 2023-05-11 at 7 06 46 PM" src="https://github.com/radiantearth/stac-browser/assets/2105468/c84bb9b1-36af-4031-b303-c72998171b3a">


Here is the full `config.js`:

```javascript
module.exports = {
    catalogUrl: "https://stac.astrogeology.usgs.gov/api",
    catalogTitle: "USGS Astrogeology Planetary ARD",
    allowExternalAccess: false, // Must be true if catalogUrl is not given
    allowedDomains: [],
    detectLocaleFromBrowser: true,
    storeLocale: true,
    locale: "en",
    fallbackLocale: "en",
    supportedLocales: [
        "de",
        "es",
        "en",
        "fr",
        "it",
        "ro"
    ],
    apiCatalogPriority: null,
    useTileLayerAsFallback: true,
    tileSourceTemplate: null,
    displayGeoTiffByDefault: false,
    buildTileUrlTemplate: ({href, asset}) => "https://tiles.rdnt.io/tiles/{z}/{x}/{y}@2x?url=" + encodeURIComponent(asset.href.startsWith("/vsi") ? asset.href : href),
    stacProxyUrl: null,
    pathPrefix: "",
    historyMode: "hash",
    cardViewMode: 'cards',
    showThumbnailsAsAssets: false,
    stacLint: true,
    geoTiffResolution: 512,
    redirectLegacyUrls: false,
    itemsPerPage: 24,
    crossOriginMedia: null,
    defaultThumbnailSize: null,
    maxPreviewsOnMap: 50,
    requestHeaders: {},
    requestQueryParameters: {},
    preprocessSTAC: null,
    authConfig: null
};
```

**Comment by jlaura** [comment]
This is now deployed to a test area here: https://stac.astrogeology.usgs.gov/browser-dev/#/ 

It appears that #320 is working as expected! 🚀

**Comment by m-mohr** [comment]
@jlaura Interesting, are you sure it's deployed? For me it doesn't work with your link (but it does locally, so I'm confused).

**Comment by jlaura** [comment]
I wonder if you aren't getting a cached version. I am invalidating the cache in cloudfront right now. It should be good in a few minutes.

**Comment by m-mohr** [comment]
Yes, works now :-)

**Comment by m-mohr** [comment]
Tests also seem successful, so will merge now.
