### ISSUE TITLE
Non root URL

### ISSUE THREAD

**Issue by tschaub** [radiantearth/stac-browser#32]
I was trying to deploy the STAC Browser at a place where it is not at the domain root.  For example, I wanted to have it someplace like https://storage.googleapis.com/example-bucket/some-prefix/stac/index.html.

Since Parcel generates absolute paths to resources by default, it doesn't work to use `npm run build` directly as that will generate an `index.html` with things like:
```html
<script src="/main.3d4dd6c5.js"></script>
```
And this doesn't work since the main bundle is not going to be at the root.

If I run parcel with ` --public-url ./`, I get a more portable `index.html`, with this:
```html
<script src="main.3d4dd6c5.js"></script>
```

This works well until I start navigating the site.  When I click on one of the items in the catalog, the client navigates to a URL like this: https://storage.googleapis.com/item/example-bucket/some-prefix/stac/index.html/Ed4DAgh7Zv45s8U25Fi7pkiMQLEzdj?t=assets

Note that `item` has been placed ahead of `example-bucket` in the path.  Since I don't control the `item` GCS bucket, this URL is not one that I can pass around to others.  And unfortunately, the owner of the `item` bucket has an account that is not in good standing, so when users go to that URL they see this:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<Error>
    <Code>UserProjectAccountProblem</Code>
    <Message>User project billing account not in good standing.</Message>
    <Details>The billing account for project 270190242553 is disabled in state absent</Details>
</Error>
```

What do others do to use the STAC Browser when it is not hosted at the root?

Thanks for your work on this project!

**Comment by mojodna** [comment]
(Apologies for this and future delays.)

I'm not aware of anyone that's deployed to a sub-path, but it certainly should support that.

Path generation and parsing in `main.js` is probably the best place to look for assumptions made that cause this behavior. (I don't have time to investigate, sorry!)

**Comment by m-mohr** [comment]
The current version on the dev branch should support this. You have to set the `publicPath` option in vue.config.js prior to rendering. Does that work for you, @tschaub ?
