### ISSUE TITLE
Supporting multiple data access points for a single asset?

### ISSUE THREAD

**Issue by cboettig** [radiantearth/stac-browser#331]
This is a bit of a conceptual as well as a technical question.  

First, on a technical side, I note that the STAC validator seems to be perfectly happy to have an array-valued `href` for an asset, e.g. [modifying the simple-item.json](https://radiantearth.github.io/stac-browser/#/external/raw.githubusercontent.com/boettiger-lab/biodiversity-catalog/befb8da344bedc0a07e2235dc1e0ca00a5e96673/simple-item.json) gives us valid STAC.  

However, as you can see in the stac-browser rendering, this breaks several aspects of stac-browser, such as the visual preview and also the download link, which (not surprisingly) seem to assume that href is not an array.  At a technical level, it might at least be desirable for the validator to object to the array-valued href given that it breaks things?

At a more conceptual level, I would really like advice on how to build a catalog where I can acknowledge that a given asset can be found in multiple places -- e.g. perhaps it is hosted both on AWS and Azure, and I want it to be clear to my Azure users to use the Azure link and users of AWS that they can use the AWS bucket link and get better performance.   Even a given source might support multiple protocols -- e.g. many STAC assets can be found in public AWS buckets that can be referenced either over the S3:// protocol or https:// protocol, as you know.  

 I think having the hrefs side-by-side would be preferable, letting the user select how best to access content.  But also I realize this probably breaks quite a lot of tooling that kinda just expects a single href.  What's the best strategy here?    Perhaps the use case of different protocols to access the same host location ought to be handled differently than a mechanism to indicate different hosts?  Or is there really a strong case to make about just having different catalogs / different JSON files for each provider / protocol?  
 
Are their any examples of a stac catalog that tries to support multi-protocol or multiple-host-location mechanism like this?

**Comment by m-mohr** [comment]
Isn't this use case what is already captured by the storage or alternate assets (and storage) extension? An array as href is invalid according to the written spec. If it validates there's either an issue in the schema or the Validator, which should be reported separately.

Once we have #262 is implemented, we can also much more easily. Implement support for the alternate assets extension in STAC Browser.

**Comment by cboettig** [comment]
ok fantastic, https://github.com/stac-extensions/alternate-assets/blob/main/examples/item.json is just what I was looking for.

I see stac browser does display this info already as https://radiantearth.github.io/stac-browser/#/external/raw.githubusercontent.com/stac-extensions/alternate-assets/main/examples/item.json?.language=en&.asset=asset-data, which I think is pretty good for our purposes.  (We often use alternate endpoints with the S3 system, looks like we can add that to description but I can follow up in the correct theme).

**Comment by m-mohr** [comment]
Yes, alternate-assets support is tbd.
