### ISSUE TITLE
GDAL VFS URLs sometimes not detected?

### ISSUE THREAD

**Issue by cboettig** [radiantearth/stac-browser#332]
My tiff assets with hrefs `/vsis3/` display nicely with the cool `GDAL VFS URL` buttons, but when I use the same prefix on, say, a GDB vector file, I get a bit more confusing button that just says 'open', presumably mistaking this for a regular path, e.g. as seen here

https://radiantearth.github.io/stac-browser/#/external/raw.githubusercontent.com/SchmidtDSE/biodiversity-catalog/main/stac/v1/collections/iucn_greenlist/collection.json?.asset=asset-spatial-polygons

![image](https://github.com/radiantearth/stac-browser/assets/222586/406c34dd-5e9d-4499-a2a0-6684b3150d9f)

Am I doing something wrong on that one?

**Comment by m-mohr** [comment]
Thanks for the report, fixed.
