### ISSUE TITLE
Translations for next release

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#333]
The next release needs a couple of new translations:

For checkboxes (I've used words from a dictionary, but want to confirm they are correct):
- `no`
- `yes`

For comparison:
- `greater than or equal to`
- `less than or equal to`

For search:
- `Match all filters (and)`
- `Match any filters (or)`

Asignees:
- [x] French @jfbourgon
- [x] German @m-mohr
- [ ] Italian @p1d1d1
- [x] Spanish @rnanclares 
- [ ] Romanian @mneagul + missing phrases in #278

Thanks all for your help!

**Comment by rnanclares** [comment]
For checkboxes (I've used words from a dictionary, but want to confirm they are correct):

    no
    si

For comparison:

    igual o mayor que
    igual o menor que

For search:

    Coincidencia con todos los filtros (and)
    Coincidencia con algún filtro (or)

**Comment by jfbourgon** [comment]
For checkboxes:
```
non
oui
```

For comparison:
```
supérieur ou égal à
inférieur ou égal à
```

For search:
```
Correspond à tous les filtres (et)
Correspond à n'importe quel filtre (ou)
```

**Comment by m-mohr** [comment]
Closing in favor of our new Localization Management Tool: https://crowdin.com/project/stac-browser
