### ISSUE TITLE
Improve rendering of openEO endpoints (paths with more than one method)

### ISSUE THREAD

**Issue by christophfriedrich** [radiantearth/stac-browser#335]
When a path has more than one method, a surplus linebreak is added to the list of methods, which makes it unclear whether this list of methods belongs to the path written above or below. For example, looking at the following screenshot one could easily think the methods for `/jobs` are GET and DELETE, although they are in fact GET and POST.

![grafik](https://github.com/radiantearth/stac-browser/assets/17781682/30307049-7c34-48f7-9850-1b5dd12e356c)

Source: https://radiantearth.github.io/stac-browser/#/external/openeo.vito.be/openeo/1.0/?.language=en

This is caused by the `content: "\a"` on the `.metadata dd::after` elements. It is necessary when there is only one method (because without it there is no linebreak between method and path), but creates this unclear situation when there is more than one method (i.e. there is a _list_ of methods). The two cases should be handled with distinct CSS rules.

**Comment by m-mohr** [comment]
This is true, but an issue of the metadata rendering library stac-fields. I can't move issues across organizations, so I'd appreciate if you could open a new issue in https://github.com/stac-utils/stac-fields

Thanks!

**Comment by christophfriedrich** [comment]
Haha, I actually even briefly looked at that repo before posting here :D Because I know how you organise stuff and already suspected that the code that does this might not be in this repo ;) But "a list of STAC fields with some metadata (title, unit, prefix) and helper functions" didn't sound like it would render anything and I saw no code that looked like Vue components. Maybe you want to update that description, e.g. by appending "[helper functions] for styling as HTML" or something like that.

**Comment by m-mohr** [comment]
Good idea, done (and fixed).

**Comment by christophfriedrich** [comment]
Don't forget to apply the same change in the repo's GitHub "About" description too ;)
