### ISSUE TITLE
Enable "prev" and "next" buttons for catalogs that implement paging links

### ISSUE THREAD

**Issue by lossyrob** [radiantearth/stac-browser#34]
While not part of the spec, some users have been using a convention to use a "next" and "prev" link in catalogs and collections to enable pagination for large sets of subcatalogs.

Enable this in stac-browser by implementing "prev" and "next" buttons for subcatalogs that operates similar to how pagination works for items.

**Comment by p1d1d1** [comment]
This also applies to items level. See here: https://sat-api.stac.cloud/A4mNqMfeBLvqieSzdXXXpmommdgKamoDJ?t=items&ip=1, pagination doesn't work

**Comment by minhtri79** [comment]
Hello,

We also implement the paging links as in the following url: https://ergo.spacebel.be/series/eo%3Aplatform/ALOS-1/TropForest. Could you please let us know is that what you expect? Thanks.

**Comment by p1d1d1** [comment]
@minhtri79 my proxy is blocking the connection to you URL because of "malware-lgd"

**Comment by ycespb** [comment]
@p1d1d1 , the same URL @minhtri79  provided above is also accessible via the STACIndex.org at https://stacindex.org/catalogs/fedeo-clearinghouse#/2cFBZJ8KrmgTfFEtXDNXJGK2i73i/3PEsgme7hQ7yLgDxuQhWkgu1C61St9qC/3cJeHHNzea9sUUveXDM46i32sgofHYhDVpEemDaus8qfu2T.  it is unclear to us whether the STACBROWSER (and which version?) already has support for prev/next links as we heavily rely on this (too many items to directly include).

**Comment by m-mohr** [comment]
STAC Index is usually aligned with STAC Browser's master branch and I PR my improvements back to STAC Browser. So if something is unsupported in STAC Browser, it's likely unsupported in STAC Index.

**Comment by ycespb** [comment]
@m-mohr thanks for the clarification;  We are still a bit puzzled by the info in the first message in this thread from @lossyrob suggesting that paging functionality may exist already, but we don't manage to find it or see an example at work (our paging links seem not picked up currently).

**Comment by p1d1d1** [comment]
So far as I could test, STAC Browser implements paging client side when it get a long list of results, but it doesn't support "api-side" paging. But I could be wrong!?

**Comment by m-mohr** [comment]
That's it exactly. I checked the code and pagination on the server-side is not supported yet. Currently, only long lists received from servers are paginated on the client-side.

**Comment by p1d1d1** [comment]
@m-mohr is there any plan to implement it?

**Comment by m-mohr** [comment]
There's currently no "paid" maintainer for STAC Browser any more AFAIK, so the project relies on contributions from interested parties like you and me and thus there are no plans for any of the issues.

**Comment by p1d1d1** [comment]
And could someone estimate how much this would need in terms of person time or money?

**Comment by m-mohr** [comment]
This has been implemented in STAC Browser v3, you can test it here: https://radiantearth.github.io/stac-browser/

**Comment by p1d1d1** [comment]
@m-mohr since few days our API (https://data.geo.admin.ch/api/stac/v0.9/) doesn't get loaded correctly: Catalogs and Items are not rendered. Have you changed something specific recently?

**Comment by m-mohr** [comment]
@p1d1d1 Sorry for the slow response, I've been on vacation. Seems I introduced a bug just before my vacation, I will check/fix this in the next week for sure.

**Comment by m-mohr** [comment]
@p1d1d1 Sorry for the slow response, I've been on vacation. Seems I introduced a bug just before my vacation, I will check/fix this in the next week for sure. I've opened a new issue to keep track.
