### ISSUE TITLE
Search page not loading

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-browser#341]
If I try to open the search page of many of the demos of STAC Browser (e.g. if I click on button Search from https://radiantearth.github.io/stac-browser/#/external/eod-catalog-svc-prod.astraea.earth ) I get an error and never see the page.

Same problem here: 
- https://radiantearth.github.io/stac-browser/#/external/tamn.snapplanet.io/
- https://radiantearth.github.io/stac-browser/#/external/data.geo.admin.ch/api/stac/v0.9/

I imagine it points to the wrong url because it points to https://radiantearth.github.io/stac-browser/#/search but I'm not sure this is the problem. I just wanted to try the search before deploying it in our infrastructure.

**Comment by m-mohr** [comment]
Hmm, I merged Collection Search into main recently, maybe that screwed some things up. I'll investigate.
You can work on the tagged version 3.0.2 until this is fixed.

**Comment by m-mohr** [comment]
Should be fixed :-)
