### ISSUE TITLE
Hide Download and "Show on map" buttons

### ISSUE THREAD

**Issue by jonas-eberle** [radiantearth/stac-browser#351]
The data in our catalog is currently not available via HTTP (only local file paths). Is there a simple possibility to hide the buttons "Download" and "Show on map" for the assets in the items page? 

![image](https://github.com/radiantearth/stac-browser/assets/2070954/be4f5d58-0f77-4e8f-8cee-ea841cd8eba2)

**Comment by m-mohr** [comment]
How do you provide the hrefs? With the `file:` protocol it should show a "Copy" button and no "Show on map" button.

It's probably something that could be improved as part of #342.

**Comment by jonas-eberle** [comment]
> How do you provide the hrefs? With the `file:` protocol it should show a "Copy" button and no "Show on map" button.

Currently without a protocol, e.g. `/folder1/folder2/file.tif`. We could test to include `file:`, if this works with GDAL, xarray and other tools.

**Comment by jonas-eberle** [comment]
Thanks. This worked so far. A small fix in the GDAL STACIT driver is already in the GDAL main branch. I will close this issue.
