### ISSUE TITLE
Relative path prefix

### ISSUE THREAD

**Issue by tschaub** [radiantearth/stac-browser#353]
I was hoping to have a single build of the browser that would work when deployed to multiple locations.  I've tried building with `--pathPrefix="./"` and `pathPrefix="."`, but neither work.

Is it possible to create a build where the deployment path is not known at build time?

**Comment by tschaub** [comment]
The [Vue docs](https://cli.vuejs.org/config/#publicpath) make this seem possible with `''` or `'./'` for a relative path.

**Comment by tschaub** [comment]
Ah, it looks like things work with `--historyMode=hash` - so just a problem configuring the router with relative paths.

**Comment by m-mohr** [comment]
As the Vue Docs state, relative URIs have problems with the history mode. Unfortunately, history mode is the preferable mode as has mode doesn't really allow indexing in Google. So ideally you would build again for different paths.
