### ISSUE TITLE
Error 404 when reloading the page / sharing a page

### ISSUE THREAD

**Issue by jfbourgon** [radiantearth/stac-browser#355]
This is more a silly question rather than a real issue. 

We have several instances of STAC Browser avaibale in our ecosystem but we are currently missing a key feature that would allow to users to bookmark a link to a specific STAC collection or a STAC item from the button available on each web pages rendered by STAC-Browser
![image](https://github.com/radiantearth/stac-browser/assets/1030226/3af7376e-71fd-46e0-81ac-e92c07eb2f36)

On our instances, this type of link is always retruning a 404 error. Our interpretation of this issue is that this link refere to a dynamic resource but our web server is interpreting this as a static resource then unable to find and serve it properly. We think we might have missed key settings either at building time or inside our current web server configuration. Would it be possible to please indicate where the relevant information could be find.

**Comment by m-mohr** [comment]
Which historyMode are you using? history or hash?
If it's `history`, you need to enable URL rewriting at the server as such:
https://v3.router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations

**Comment by m-mohr** [comment]
I'll make this more clear in the docs, thanks.

**Comment by m-mohr** [comment]
Details can be found here now: 
https://github.com/radiantearth/stac-browser/blob/main/docs/options.md#history
