### ISSUE TITLE
HTTP Code 404 returned on inactive JavaScript

### ISSUE THREAD

**Issue by sustr4** [radiantearth/stac-browser#361]
When accessing the STAC browser with a Web browser that does not have JavaScript enabled, a web page with an apology is given in response, **but** the HTTP response code returned with it is **404 Not Found**. This is not correct (the resource was found) and confuses automated tools such as monitoring probes.
Instead of 404, another suitable, more fitting response code should be returned, probably from the 200 series.

**Comment by m-mohr** [comment]
STAC Browser doesn't send any HTTP status codes itself as far as I'm aware.
I can't reproduce it either. If I disable JS in Chrome and request the demo instance on GitHub, the server responds with a 304. So sounds like a server configuration issue to me unless you can provide me with a reproducible example.

**Comment by sustr4** [comment]
No, I cannot reproduce this with the GitHub instance. On further investigation the reason for my issue seems to be elsewhere, specifically in the different handling of:
https://radiantearth.github.io/stac-browser -- which returns **301 Moved Permanently**, vs.
https://radiantearth.github.io/stac-browser/ -- which returns **200**

In my local installation I get 404 rather than 301, if I use, e.g., `curl` without the trailing slash. A graphical browser such as Firefox copes with either.  This issue can probably be closed as something outside the domain of STAC-browser.
