### ISSUE TITLE
Collection page: display collection ID

### ISSUE THREAD

**Issue by ktiits** [radiantearth/stac-browser#363]
On Collection page currenlty Collection ID is visible only from page URL, but for many users planning to switch from STAC Browser to Python/R/etc it is important to easily see also Collection ID.

**Comment by m-mohr** [comment]
Great suggestion! You can find it in the Source tab now, including a simple way to copy it.

![grafik](https://github.com/radiantearth/stac-browser/assets/8262166/914187d5-74c5-467b-b98c-1aeb5b43750d)
