### ISSUE TITLE
pathPrefix option

### ISSUE THREAD

**Issue by SerRichard** [radiantearth/stac-browser#367]
The pathPrefix option is listed as build only, for anyone deploying in a cloud environment the likelihood is the server will run behind a proxy. I'm able to set other configuration options using the edit in index.html as mentioned in the docs and this works fine. Is there any possibility that the pathPrefix option can be configured without requiring a rebuild of the container?

**Comment by m-mohr** [comment]
No, this is a limitation by Vue. You can use runtime-config options but otherwise we are out of luck.
See https://github.com/radiantearth/stac-browser/blob/main/docs/options.md#options
