### ISSUE TITLE
cogeo.xyz deprecation

### ISSUE THREAD

**Issue by vincentsarago** [radiantearth/stac-browser#368]
Hi,
Just to let you know that the `https://cogeo.xyz` website and api are deprecated and will be teared down in couple days. Please make sure to switch to `https://titiler.xyz` (Developmentseed demonstration endpoints) or deploy your own tile server (https://developmentseed.org/titiler/) 

https://github.com/radiantearth/stac-browser/blob/6140a26b94b63a59dbce663e7a0d28849efcb54c/src/actions/assets/CoGeoXyz.js#L13

**Comment by m-mohr** [comment]
Thanks for letting me know, just a day too late afer release, dang.
I'll remove the cogeo.xyz integration after my vacation. 
If anyone in the meantime wants to come up with a PR, I'm happy to merge it.
