### ISSUE TITLE
Show collection level assets

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-browser#38]
The [collections assets](https://github.com/radiantearth/stac-spec/tree/master/extensions/collection-assets) extension is new with 1.0.0-beta.1, and enables addition of thumbnails and metadata assets at the collection level. It'd be great to show those assets in the same way that items do - visualizing the thumbnail and giving download links to the assets. Can test with https://ergo.spacebel.be/ For example https://ergo.spacebel.be/series/eo:organisationName/VITO/urn:ogc:def:EOP:VITO:PROBAV_L2A_100M_V001

**Comment by m-mohr** [comment]
I guess that doesn't even need much additional code if the asset code is just put into a new component or mixin and used in two places...
