### ISSUE TITLE
items link does not include collection

### ISSUE THREAD

**Issue by pvgenuchten** [radiantearth/stac-browser#384]
First a more general question; does stac-browser also aim to support ogcapi:records, since stac and ogcapi-records are quite similar? 
This question relates to my observation that stac browser is capable to handle initial queries to a ogcapi-records endpoint...

https://radiantearth.github.io/stac-browser/#/external/demo.pygeoapi.io/master/collections/dutch-metadata?f=json

But then when the list of items is displayed, for each item stac-browser links to an item without its collection in the url.

![image](https://github.com/radiantearth/stac-browser/assets/299829/715fde0d-d66e-4e55-b4a3-6c6619cd1625)

links to:
- https://radiantearth.github.io/stac-browser/#/external/demo.pygeoapi.io/master/collections/items/364c5d7a-d6ec-11ea-87d0-0242ac130003

expected is: 
- https://radiantearth.github.io/stac-browser/#/external/demo.pygeoapi.io/master/collections/dutch-metadata/items/364c5d7a-d6ec-11ea-87d0-0242ac130003

Is this a bug, or is this the aspect on which stac and ogcapi:records differ?

**Comment by pvgenuchten** [comment]
I just noticed that this pygeoapi service does not provide a self link on items in a items response, maybe this causes the behaviour?

https://demo.pygeoapi.io/master/collections/dutch-metadata/items?f=json&limit=12

see also https://github.com/geopython/pygeoapi/issues/1384

**Comment by m-mohr** [comment]
In general, OGC API Records and Features should be mostly working with STAC Browser, but there is no official support yet. That means I don't necessarily test all changes against OGC APIs so things can unexpectedly break. Experience shows that issues with links usually occur from invalid server implementations. Here it looks like that trailing slashes are missing in the links.

**Comment by pvgenuchten** [comment]
this can indeed be a trailing slash issue, seems stac-browser expects a trailing slash at `collections/foo/`

**Comment by m-mohr** [comment]
Indeed, because otherwise it is considered being a file and as such URL resolving techniques fail.
