### ISSUE TITLE
Histogram is not displayed for all assets with the asset extension

### ISSUE THREAD

**Issue by mneagul** [radiantearth/stac-browser#385]
The raster extension does not seem to work for all raster assets. It works fine for standard RGB (ubyte8) but for other not.

An example is available here:
 - Does not work: https://browser.sage.uvt.ro/#/collections/sentinel-2-l2a-maja/items/SENTINEL2A_20230922-091803-561_L2A_T35TMK_C?.asset=asset-FRE_B11
 - It works: https://browser.sage.uvt.ro/#/collections/sentinel-2-l2a-maja/items/SENTINEL2A_20230922-091803-561_L2A_T35TMK_C?.asset=asset-FRE_TCI

**Comment by m-mohr** [comment]
The issue is that it doesn't start rendering tables for less than 3 bands/rows and only the table view supports charts for histograms.

**Comment by mneagul** [comment]
This is what I was suspecting (after submitting the bug report). It would be nice to see histograms also for single channel data. In a few weeks I cloud try to contribute this.

**Comment by m-mohr** [comment]
Table rendering will be enforced now for eo:bands and raster:bands
