### ISSUE TITLE
/items response content-type

### ISSUE THREAD

**Issue by mhogeweg** [radiantearth/stac-browser#394]
cross-posting between this and the STAC spec repo https://github.com/radiantearth/stac-spec/issues/1265

there appears to be room for interpretation as to whether the /items API resource should return application/json or application/geo+json. The former is used for catalog, collections, and several others. the latter is used for an individual item. /items returns a geojson feature collection consisting of items.

currently it appears that stac-browser requires application/json. 

is stac-browser correct? or should the /items response be application/geo+json since it is a geojson feature collection?

**Comment by mhogeweg** [comment]
this is visible when the STAC Browser makes the /items request:

https://radiantearth.github.io/stac-browser/#/external/geoportalstac.azurewebsites.net/stac/collections/metadata

the request to:
https://geoportalstac.azurewebsites.net/stac/collections/metadata/items?limit=12

includes header Accepts: application/json

![image](https://github.com/radiantearth/stac-browser/assets/394890/d8bdee74-9cb2-4e4a-8f90-27be10c5c052)

**Comment by m-mohr** [comment]
@mhogeweg STAC Browser uses whatever you expose. The link inhttps://geoportalstac.azurewebsites.net/stac/collections/metadata is application/json as such it uses that. It's a bug in the API implementation.

**Comment by m-mohr** [comment]
No, STAC Browser is not requiring `application/json`.

**Comment by m-mohr** [comment]
For an example how it correctly works check MS Planetary Computer. It shows that STAC Browser can handle it correctly and it's likely an API bug in Geoportal.

**Comment by mhogeweg** [comment]
this is what we were seeing before the switch to application/json:

![image](https://github.com/radiantearth/stac-browser/assets/394890/981915e8-fa3c-470e-bf9f-8db1842c6ec2)

**Comment by m-mohr** [comment]
That's no proof. It's pretty sure an API bug, see MS PC for an implementation where it's implemented correctly and also works correctly. If you need help with fixing your API, feel free to reach out for consulting.
