### ISSUE TITLE
Http 400 error on Item Search with SortBy specified

### ISSUE THREAD

**Issue by juliayun23** [radiantearth/stac-browser#402]
We are using stac-browser on top of [stac-fastapi](https://github.com/stac-utils/stac-fastapi). Recently during testing, I noticed that when doing item search, if I specify an option (any option apart from `Default`) in "Sort" dropdown list, it returns `400`

![Screenshot 2024-01-12 at 2 39 58 pm](https://github.com/radiantearth/stac-browser/assets/4505336/c6e048cc-e6d2-44c6-ac5a-c0d5609d3849)

The response is:
```
{
    "code": "RequestValidationError",
    "description": "[{'loc': ('body', 'sortby'), 'msg': 'value is not a valid list', 'type': 'type_error.list'}]"
}
```

**Comment by juliayun23** [comment]
Happy to submit a PR if this is confirmed as a bug.

**Comment by m-mohr** [comment]
Yes, this is a bug.

STAC Browser sends:
`"sortby":"properties.title"`

It should be:
```
    "sortby": [
        {
            "field": "properties.title",
            "direction": "asc"
        }
    ]
```

**Comment by juliayun23** [comment]
> Yes, this is a bug.
> 
> STAC Browser sends: `"sortby":"properties.title"`
> 
> It should be:
> 
> ```
>     "sortby": [
>         {
>             "field": "properties.title",
>             "direction": "asc"
>         }
>     ]
> ```
> 
> A PR would be very welcome.

@m-mohr May I pls have write access to the repository to push my dev branch and create the PR? Thanks.

**Comment by juliayun23** [comment]
@m-mohr Thanks. PR ready for your review https://github.com/radiantearth/stac-browser/pull/406.
