### ISSUE TITLE
stac-browser sometimes define an URL as external with no reason

### ISSUE THREAD

**Issue by keul** [radiantearth/stac-browser#403]
# The problem

Let say I start the stac-browser (in this example in development mode, but is the same with build) as follows:

```
npm start -- --open --catalogUrl="/api/catalogue/v1/" --pathPrefix=/stac-browser/
```

As you can see, I use a relative `catalogUrl` parameter.

After that, I proxy everything (a website, the stac-browser and the STAC API) behind nginx.

So I can access:

- https://mydomain (website)
- https://mydomain/stac-browser/ (stac-browser instance)
- https://mydomain/api/stac/v1/ (STAC rest API)

Everything works, but URLs generated by stac-browser when clicking on (for example) a collection, are recognized as "external".
They are all like: `https://mydomain/stac-browser/external/https:/mydomain/api/catalogue/v1/collections/my-collection`

Please note: **links are working**, but I would expect them to be like: `https://mydomain/stac-browser/collections/sis-marine-properties`

In facts, if I run the stac-browser as follows, everything is as I expects, URLs are reconized as "internal":

```
npm start -- --open --catalogUrl="https://mydomain/api/catalogue/v1/" --pathPrefix=/stac-browser/
```

# A bit of context (AKA: why this is a problem?)

We are deploying many different STAC APIs with dedicated stac-browsers on a general kubernetes infrastructure. Knowing in advance the final URL of the stack is not easy and error prone.

Being able to define API URL using a root-relative path is a big plus. At the same time, having the domain in the "external" URL is a problem because we want to automatically build links to STAC elements from the https://mydomain/ website

# Technical analysis

~Unluckily I'm not expert on Vue, but I think that problem is on the `isExternalUrl` method here~

After trying again, the problem seems in the caller `toBrowserPath`, but really hard to understand what is going on here.

**Comment by m-mohr** [comment]
The catalogUrl must be a full URLs with a host according to the docs (implicit through "The URL provided here must match exactly with the href that is provided as self link in the response body of the URL." - self links are required to be absolute). As such rel/abs paths were never tested and are not supported. 

Did you consider the option to provide the catalogUrl dynamically at runtime or via a function in the config file?

**Comment by keul** [comment]
Well, that's the problem in my environment. Not easy to provide it at runtime (tons of k8s layering in a complex network), but I understand the limitation.

I found a way to hack this but changing the mutation inside the `store` module:

```
            case "catalogUrl":
              if (typeof value === "function") {
                state.catalogUrl = value();
              } else if (typeof value === "string") {
                if (value.startsWith("/") && !value.startsWith("//")) {
                  // if catalogueUrl has been defined as a relative path,
                  // let's use current browser URL to build the full path
                  const url = new URL(window.location.href);
                  state.catalogUrl = `${url.protocol}//${url.host}${value}`;
                } else {
                  state.catalogUrl = value;
                }
              }
              break;
```

It's hacky, but I understand it's a corner case. I'll try to `sed` this on our docker image.

**Comment by keul** [comment]
> Did you consider the option to provide the catalogUrl dynamically at runtime or *via a function in the config file?*

Ah, this can be handy. If it works, can be less hacky

**Comment by m-mohr** [comment]
I've used it in the past for an instance, it should work. If not please let me know @keul
