### ISSUE TITLE
Switching language doesn't get applied to heading

### ISSUE THREAD

**Issue by christophfriedrich** [radiantearth/stac-browser#428]
As you can see in the screenshot for my previous issue #427, for which I changed the display language from German to English, the language change is not applied to the heading ("Suche" remains "Suche" and not "Search")

![grafik](https://github.com/radiantearth/stac-browser/assets/17781682/4718ea2f-86d7-4fed-bc92-2485f8fd5660)

Keyword: i18n

**Comment by m-mohr** [comment]
Good catch, thanks. Has been fixed in ed7c1e24
