### ISSUE TITLE
Docker image not available to pull from ghcr

### ISSUE THREAD

**Issue by hrodmn** [radiantearth/stac-browser#433]
I am authenticated with `ghcr.io` but when I try pulling the image I get `denied`!

```sh
$ docker pull ghcr.io/radiantearth/stac-browser:latest
Error response from daemon: denied
```

**Comment by m-mohr** [comment]
The GHCR image was an external contribution, I honestly have no clue how it works. Maybe @tschumpr can help?

**Comment by m-mohr** [comment]
I found out that the visibility of the package is set to private. I need to talk to the Radiant Earth Team to get that changed. Stay tuned!

**Comment by m-mohr** [comment]
@hrodmn Should work now. If it still doesn't work, please comment here again. Thanks for the report.
