### ISSUE TITLE
apply filters recursively

### ISSUE THREAD

**Issue by wiesehahn** [radiantearth/stac-browser#452]
Would it make sense and be possible to apply the filtering ("Filter Catalogs by title, description or keywords") not just at the current collection level but recursively at collections within collections. 

Lets say e.g. at https://radiantearth.github.io/stac-browser/#/external/earthengine-stac.storage.googleapis.com/catalog/catalog.json?.language=en we would like to query catalogs/collections related to fire. 
If we search for "fire" at this level the only catalog we find is `LANDFIRE`, however the underlaying catalog of `FIRMS` has the keyword "fire" as well and I think it would be nice to (optionally) list all catalogs/collections which have children with respective keywords, titles.

**Comment by m-mohr** [comment]
Please note that this is client-side filtering functionality. That would indeed be nice but would require that all children are loaded to the client upfront, which may hit the server with hundreds of requests depending on the structure. As such this seems unfeasible and can't be implemented in a reasonable way, sorry.

**Comment by wiesehahn** [comment]
Ah yeah thanks for explanation, I was thinking more about a couple of catalogs with another couple of subcatalogs at the first level, which would require to load less than a hundred json files in memory. But makes sense. 

I guess another alternative would be to push keywords to parent catalogs as well when creating them.
