### ISSUE TITLE
Cannot read properties of undefined (DatePickerMixin)

### ISSUE THREAD

**Issue by drnextgis** [radiantearth/stac-browser#454]
When I open a collection, I encounter one of the following errors. The first occurs when I click on the collection name from the Catalogs page, and the second appears if I refresh the Collection page (in this case, `?.language=en` is automatically added to the URL).

```javascript
TypeError: Cannot read properties of undefined (reading 'locale')
    at a.handler (DatePickerMixin.js:24:21)
```

```javascript
TypeError: Cannot set properties of undefined (setting 'firstDayOfWeek')
    at 71865 (datepicker.js:6:21)
    at a (bootstrap:19:32)
    at datepicker\.js$ namespace object:74:10
    at async a.handler (DatePickerMixin.js:23:15)
```
For [example](https://radiantearth.github.io/stac-browser/#/external/capella-open-data.s3.us-west-2.amazonaws.com/stac/capella-open-data-by-datetime/capella-open-data-2020/capella-open-data-2020-12/capella-open-data-2020-12-01/catalog.json?.language=en).

**Comment by m-mohr** [comment]
Should be fixed, thanks for the report.
