### ISSUE TITLE
Option "client_id" is not read for authConfig openIdConnect

### ISSUE THREAD

**Issue by jgaucher-cs** [radiantearth/stac-browser#459]
Hello, when testing the STAC browser with an OpenID authentication, I think there is a mistake in the source code: the `client_id` option is hardcoded to "stac-browser".

Here the documentation says how to configure the `client_id` option: <https://github.com/radiantearth/stac-browser/blob/main/docs/options.md#openid-connect>
```yaml
{
  type: 'openIdConnect',
  openIdConnectUrl: 'https://stac.example/.well-known/openid-configuration',
  oidcOptions: {
    client_id: 'abc123'
  }
}
```

There in the source code, we see that the `openIdConnectUrl` field is read from the user input option, but the `client_id` is hardcoded: <https://github.com/radiantearth/stac-browser/blob/108947ebe8cbd64c7e288bbaa3c5f81293706d3e/src/auth/oidc.js#L13>
```js
    const oidcConfig = {
      authority: options.openIdConnectUrl.replace('/.well-known/openid-configuration', ''),
      client_id: 'stac-browser',
```

Before running the STAC browser, I'm changing the "config.js" file to set:
```yaml
authConfig: { "type": "openIdConnect", "description": "KeyCloak OpenId authentication", "openIdConnectUrl": "https://<my-openid-domain>/realms/rspy/.well-known/openid-configuration", "oidcOptions": {"client_id": "my_openid_client_id"} }
```

Then when running the STAC browser, my personal OpenID domain is well read, but the `client_id` is hardcoded to "stac-browser":

![keycloak](https://github.com/user-attachments/assets/75cb5982-64d9-4994-bece-9bd53c770cbd)

What do you think about this ? Thank you :)

**Comment by m-mohr** [comment]
The README was outdated, you need to provide oidcConfig instead of oidcOptions and it should work.
