### ISSUE TITLE
Collection Search Endpoint Not Showing in STAC Browser

### ISSUE THREAD

**Issue by dmistry1** [radiantearth/stac-browser#481]
Hi, I'm currently working with the STAC Browser and encountering an issue where the collection search is not showing up as expected.

- I have the item search working correctly under `/search`, and it shows up in the STAC Browser without issues.
- My collection search is set up under `/id/collection/search`, but it doesn't appear or work in the STAC Browser.
- I have added the collection-search extension to my API and ensured it is included in the conformance array:
```"https://api.stacspec.org/v1.0.0/collection-search"```

Steps I’ve Taken:

- Verified that the collection search endpoint works correctly when queried directly.
- Ensured that the conformance URL for collection-search is included in the API.
- Tried setting up /collections/search instead of my custom route but still didn’t see it show up in STAC Browser.

Expected Behavior: I expect the collection search endpoint to be recognized and displayed in STAC Browser in a similar way to how the item search works.

I’ve seen that collection search has been implemented in STAC Browser as mentioned in [issue #249](https://github.com/radiantearth/stac-browser/issues/249).

Looking at the STAC Browser codebase locally, I see there is an index.js where `getters.supportsConformance(TYPES.Collections.BasicFilters)` seems to correctly find the collection search, but I’m not seeing the tab for collection search in the UI

![image](https://github.com/user-attachments/assets/e7cc3d03-db00-4210-88ae-0d4eef1e223c)

Is there anything specific I need to configure to make the STAC Browser recognize my collection search endpoint? Or does STAC Browser require the route to strictly be /collections/search?

Thanks in advance for your guidance!

**Comment by m-mohr** [comment]
Collection Search must be implemented at /collections, it's just an extension of the normal Collection List endpoint.
