### ISSUE TITLE
MissingPointerError: Token "fieldsproperties" does not exist

### ISSUE THREAD

**Issue by drnextgis** [radiantearth/stac-browser#482]
When I open a collection page I see this in the console:
![image](https://github.com/user-attachments/assets/c857c168-36d2-4f9d-bd32-faef9df8350a)

**Comment by m-mohr** [comment]
That looks like an error in the Queryables, STAC or extension schema.
Is it potentially this? https://github.com/stac-utils/pgstac/issues/193
