### ISSUE TITLE
Wrong API endpoint for cql2-text filters

### ISSUE THREAD

**Issue by drnextgis** [radiantearth/stac-browser#483]
While using stac-browser for a search, it applies the `cql2-text` filter, but it hits the incorrect API endpoint:

```
/collections/{collection_id}/items?filter-lang=cql2-text&filter=...
```

The correct endpoint should be:

```
/search?collections={collection_id}&filter-lang=cql2-text&filter=...
```

**Comment by m-mohr** [comment]
Which search are you using? Can you post a screenshot of the search UI?

**Comment by drnextgis** [comment]
From this page it works fine:
![image](https://github.com/user-attachments/assets/36e5083d-976e-49b3-8175-b0409e322ea0)


From this page it doesn't work:
![image](https://github.com/user-attachments/assets/d0575962-6105-4580-ba2f-6f1bc94c820e)

**Comment by m-mohr** [comment]
That is correct behaviour. You are targeting the Collection-specific item search in this part.

**Comment by drnextgis** [comment]
Thank you @m-mohr. I’ve created a ticket in the stac-fastapi repository.

**Comment by m-mohr** [comment]
Because you are searching through what was returned for a specific collection. We are searching the endpoint that we got the data from that you are seeing.
