### ISSUE TITLE
Collection id not added to base URL for OGC API Features

### ISSUE THREAD

**Issue by dblodgett-usgs** [radiantearth/stac-browser#486]
I scanned through open issues and didn't see anything that stood out to document this.

To reproduce, see: 

https://radiantearth.github.io/stac-browser/#/external/reference.geoconnex.us/collections/hu10?f=json

go to one of the features and notice that the collection id is dropped:

https://radiantearth.github.io/stac-browser/#/external/reference.geoconnex.us/collections/items/0101000204

but if we add the collection id back we get:

https://radiantearth.github.io/stac-browser/#/external/reference.geoconnex.us/collections/hu10/items/0101000204

**Comment by m-mohr** [comment]
Has been identified as being a server issue, base self-link was incorrectly missing a trailing slash. See also https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#consistent-uris

**Comment by dblodgett-usgs** [comment]
Maybe I'm missing something. I see that the stac browser is requesting the conformance document for the server and getting the collections from the server. It then shows the OGC API Features collections that are compatible with the STAC API as if they will work. A user navigates into what they expect to work and get an error.

It seems like we should be able to use conformance / openapi to determine how to deal with trailing slashes in the case that we are dealing with OAF items vs STAC items. Is this not possible?

![image](https://github.com/user-attachments/assets/4a61f106-2b4c-413f-8dbb-345f4a397d9f)

**Comment by m-mohr** [comment]
How to handle trailing slashes is not determined by an OpenAPI document. It is defined by the IETF and you have to follow it if you want to be STAC compliant. I'm not sure how conformance classes relate to this.

**Comment by dblodgett-usgs** [comment]
OK, so since the conformance section of the OGC-API in question does not state that the API is STAC compliant, shouldn't that trigger a more nuanced approach to trailing slashes? Should there be a way to declare that the server is STAC compliant to avoid trying to represent OGC-API Features as if it were a STAC catalog?

I'm having a hard time following your hard stop attitude to trailing slashes here.

**Comment by m-mohr** [comment]
This has nothing to do with STAC or me.

This is defined by IETF RFC 1808 and also applies to OGC standards. We just follow the standard, no attitude here.

**Comment by dblodgett-usgs** [comment]
Apologies for the impression that I'm being negative toward you -- I did not intend to come off that way. 

It seems that there is confusion about implementation of links in OGC-API Features. I see that you've engaged over in the issue I linked above. Thanks.

**Comment by dblodgett-usgs** [comment]
OK, I tracked this down to this.

This gets called https://github.com/radiantearth/stac-browser/blob/main/src/store/index.js#L851

`url = Utils.toAbsolute(`items/${item.id}`, baseUrl);`

and makes its way down to this: https://github.com/radiantearth/stac-browser/blob/main/src/utils.js#L151

If baseUrl there has a / at the end, `urijs.absoluteTo` returns the value of baseUrl otherwise, it strips the basename of the path as would be expected.

But in this case, since `items/$item.id}` is a relative URL constructed in code and baseUrl may not have been constructed expecting that it would be used as a baseUrl in this way. 

I'm not going to claim to know how to fix the issue, but this does seem to be what's going on that's causing the trip up.

**Comment by RichFrazier** [comment]
@m-mohr any luck fixing the problem @dblodgett-usgs noted.  We have been working with a large community of users and they all keep reporting the same issue.

**Comment by dblodgett-usgs** [comment]
This is not an issue of incorrect API implementations. `stac-browser` attempts to interpret OGC-API as STAC but it doesn't support OGC-API. There is an assumption encoded in `stac-browser` as I illustrate just above. That assumption is leading to a misrepresentation of OGC-API.

Until the underlying incompatibility of STAC and OGC-API is resolved it's a bad look to have partially functioning representations of OGC-API in stac-browser. I would prefer that stac-browser not work at all instead of partially functioning as it does in the examples below.

here's an OGC-API as pygeoapi represents it that includes a STAC catalog that renders in a very misleading way. https://radiantearth.github.io/stac-browser/#/external/api.water.usgs.gov/gdp/pygeoapi

here's an OGC-API as ESRI represents it that @RichFrazier passed along recently. https://radiantearth.github.io/stac-browser/#/external/ngda-portfolio-community-geoplatform.hub.arcgis.com/api/search/v1?.language=en

**Comment by m-mohr** [comment]
Here's a long explanation, why this is so difficult and can't easily be solved here without a lot of hardocding and (potentially wrong) assumptions: https://github.com/opengeospatial/ogcapi-common/issues/354#issuecomment-3110524258

**Comment by m-mohr** [comment]
I've created a PR that solves the issue, I think. It's doing a lot of manual URI wrangling and I don't ever want to work on this flawed OGC stuff anymore.
