### ISSUE TITLE
Search functionality redirects inconsistently

### ISSUE THREAD

**Issue by drnextgis** [radiantearth/stac-browser#489]
1. Navigate to [this URL](https://radiantearth.github.io/stac-browser/#/external/catalogue.dataspace.copernicus.eu/stac/).
2. Select the "Search" option.

Occasionally, it may:
- Redirect to https://radiantearth.github.io/stac-browser/#/search ([example](https://github.com/user-attachments/assets/acd7b23e-2b88-4f1d-872e-f3b58d31e5ea))
- Redirect to https://radiantearth.github.io/stac-browser/#/search/external/catalogue.dataspace.copernicus.eu/stac but display the message "Item Search is not supported by the API." ([example](https://github.com/user-attachments/assets/841d4c5f-05d6-4167-8de7-ed1a9aa31c5a))

**Comment by drnextgis** [comment]
We've also started receiving the message "Item Search is not supported by the API" for our non-public STAC catalog, and collections are now inconsistently populated. This is the first time I've encountered this issue.

**Comment by m-mohr** [comment]
Please, could you check whether this was already the case before commit https://github.com/radiantearth/stac-browser/commit/cce41cfcf2c4faf05e93a5418c7235b3ec382c8d from yesterday?

**Comment by drnextgis** [comment]
I can confirm that with the d10fc7d commit, the issue of an empty list of collections on the search page no occurs.

![d10fc7d](https://github.com/user-attachments/assets/1d11f398-e65e-429a-96d4-9371b6a7d388)

![latest](https://github.com/user-attachments/assets/d39ece25-7471-4526-b7e8-604a28d0e452)

**Comment by drnextgis** [comment]
Thank you, @m-mohr! It looks like the issue with collections is resolved, as I can no longer reproduce it. However, the "search" function is still acting up. I checked the type (see the attachment), and the 'search' link is showing as 'application/geo+json', but I’m still getting the error message: 'Item Search is not supported by the API'. Interestingly, if I refresh the page, the search starts working, and I can see the input fields.

[Screencast from 16-10-24 09:19:22.webm](https://github.com/user-attachments/assets/fcac832b-2f35-4114-aa6d-c1ae02448f4b)

**Comment by drnextgis** [comment]
It might have been a caching issue, as I can’t reproduce the problem with 'search' in a private tab. I believe the ticket can be closed. Thank you!

**Comment by m-mohr** [comment]
Ok, let me know if it occurs again.
