### ISSUE TITLE
Map not shown

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#49]
When browsing through catalogs / items with STAC Browser, sometimes the console shows errors such as:
* Error: Map container not found.
* Error: Map container reused...

That sounds a bit like when switching between Items some map related state is not cleared.

**Comment by lossyrob** [comment]
I'm unable to duplicate this locally. Can you give some reproduction steps?

**Comment by m-mohr** [comment]
@ycespb Can you remember a repro?

**Comment by ycespb** [comment]
@m-mohr , I don't manage to reproduce the problem.  If I see it again, I'll note down the steps to get there.. Sorry.

**Comment by ycespb** [comment]
@m-mohr, when using the "back" button from the browser (not the best way to reproduce).  Go to https://geo.spacebel.be/2cFBZJ8KrmgTfFEtXDNXJGK2i73i/J55iKsUgAHLDvxq9kfTQMXqBu6UcYDyyUk3WhfhvK8oQyqEzUcwS?t=catalogs  (which presents the info at https://ergo.spacebel.be/series/eo%3Aplatform/CALIPSO%20(Proteus)) .  The map is shown.  Click on one of the 4 collections (they have a problem we still have to fix).  Use the browser back-button.  You get back to the page with the 4 collections but the map is missing. Reload the page.  The "map" is shown again.  Would be nicer to reproduce the problem in a nominal scenario as well...

**Comment by lossyrob** [comment]
@ycespb I tried to follow these steps and I was unable to reproduce. What browser are you using?

**Comment by m-mohr** [comment]
I can't reproduce either anymore. Maybe things have changed in the meantime, not sure...
