### ISSUE TITLE
Filter-based sorting does not work for single page collections 

### ISSUE THREAD

**Issue by LeoBreebaart** [radiantearth/stac-browser#491]
If you browse to a collection that allows spatiotemporal item filtering, and the total number of items in the collection fits on the default page (i.e. less then 12), then opening the Filters dialog and choosing a different 'Sort' order has no effect. Only if the results are more than a page long does the list shown reorder its items.

Example: [https://radiantearth.github.io/stac-browser/#/external/emc.spacebel.be/collections/F-FCC](https://radiantearth.github.io/stac-browser/#/external/emc.spacebel.be/collections/F-FCC)

**Comment by m-mohr** [comment]
I don't get a sort field shown in your example:
![grafik](https://github.com/user-attachments/assets/c170b7d7-ed86-4f10-ad57-235c8ff1ccd8)
Can you clarify, please?

**Comment by LeoBreebaart** [comment]
> I don't get a sort field shown in your example:

Heh, I think that's because you're actually being bitten here by the bug I reported in https://github.com/radiantearth/stac-browser/issues/490 :-)

If, on the page you screenshotted, you click the 'Up' button, and then re-enter the False Colour Composites collection again, the filter options will appear. Or at least they do for me:

<img width="1489" alt="image" src="https://github.com/user-attachments/assets/63d4bdd0-d8a0-4efd-8759-836559d1d32c">

Regards,

-- Leo

**Comment by m-mohr** [comment]
Ah yeah, I can reproduce it now. Will have a look.

**Comment by m-mohr** [comment]
Has been fixed in fcc20f22
