### ISSUE TITLE
Catalogs search box and keywords list missing

### ISSUE THREAD

**Issue by itrnd** [radiantearth/stac-browser#505]
The main page top catalogs filtering search box and keywords drop-down list are no longer visible. This happened as soon as we implemented collections pagination in our STAC API.
I was able to reproduce this issue with other public API's:
`docker run --rm --name fedeo -d -p 8081:8080 -e SB_catalogUrl="https://emc.spacebel.be/" stac-browser:v1`
As it can also be seen here: https://radiantearth.github.io/stac-browser/#/external/fedeo.ceos.org/

**Comment by m-mohr** [comment]
The search box + collection keywords work only client-side and as such can only work when all data is available to the client directly, which is not the case once pagination is enabled. In this case you have to use the Collection Search extension.
