### ISSUE TITLE
Search: Dropdown is hidden

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#508]
> The current dropdown appears like this, with the third item hidden behind the sort input.
![image](https://github.com/user-attachments/assets/071847ef-7626-41d8-8cb9-1754813dbb06)

_Originally posted by @drnextgis in https://github.com/radiantearth/stac-browser/issues/495#issuecomment-2492190563_

**Comment by m-mohr** [comment]
I think I fixed it, but the z-index and positioning of "external" components (like timepicker, multiselect, map, dropdown) are a bit a pain in the butt to organize so not claiming it's perfect ;-)

**Comment by drnextgis** [comment]
Thank you Matthias!
