### ISSUE TITLE
Items not loaded when visiting a Catalog for a second time

### ISSUE THREAD

**Issue by graves-k** [radiantearth/stac-browser#509]
The Items for a Catalog/Collection are not loaded when navigating to that same Catalog/Collection for a second time.

## Steps to reproduce

1. Start [here](https://radiantearth.github.io/stac-browser/#/external/planetarycomputer.microsoft.com/api/stac/v1/collections/io-lulc-9-class)
2. Click `Up` to go to parent
3. Click the `10m Annual Land Use Land Cover (9-class) V1` catalog
4. The Items are not loaded on the second visit to the same catalog

## Screenshots

First visit of Catalog:

![image](https://github.com/user-attachments/assets/6a9d988c-8e87-4d56-815f-075369b919dd)

Navigate to parent and then go back to same child:

![image](https://github.com/user-attachments/assets/82f51284-36a0-4972-89e9-d956a373c3ef)

**Comment by m-mohr** [comment]
Thanks, that's confirmed. I'll have a look.

**Comment by m-mohr** [comment]
That should be fixed, thanks for reporting it.
