### ISSUE TITLE
Show thumbnails in collection view if collection assets contain a thumbnail

### ISSUE THREAD

**Issue by lossyrob** [radiantearth/stac-browser#52]
Per [this comment](https://github.com/radiantearth/stac-browser/pull/47#issuecomment-696210448) on PR #47 in which collection assets were implemented, implement the "thumbnail" tab similarly to how it is implemented in the Item view if a collection asset contains a thumbnail.

If someone has a public STAC that has collections with ~~summaries~~ assets containing a thumbnail, please comment the HREF in the issue for testing!

**Comment by m-mohr** [comment]
http://earthengine.openeo.org/v1.0/collections/AAFC/ACI for example. Under http://earthengine.openeo.org/v1.0/collections there are more...

**Comment by m-mohr** [comment]
Implemented in dev.
