### ISSUE TITLE
Directory not empty error, Vue package version mismatch on "npm start"

### ISSUE THREAD

**Issue by charlesbluca** [radiantearth/stac-browser#54]
When running `npm start -- --open` to begin running a server, I get a "directory not empty" error:

```
> stac-browser@0.6.2 start /mnt/c/Users/charlesbluca/Desktop/pangeo/stac-browser
> npm run clean && parcel --target=browser index.html "--open"


> stac-browser@0.6.2 clean /mnt/c/Users/charlesbluca/Desktop/pangeo/stac-browser
> find dist ! -name _redirects -delete

find: cannot delete ‘dist’: Directory not empty
```

I'm able to get around this by editing the [`clean`](https://github.com/radiantearth/stac-browser/blob/master/package.json#L9) script to exclude directories, but after finishing this step a build error occurs due to mismatched Vue package versions:

```
🚨  /mnt/c/Users/charlesbluca/Desktop/pangeo/stac-browser/src/components/Catalog.vue: 

Vue packages version mismatch:

- vue@2.6.12 (/mnt/c/Users/charlesbluca/Desktop/pangeo/stac-browser/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/mnt/c/Users/charlesbluca/Desktop/pangeo/stac-browser/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
```

I was also able to get around this by bumping the [`vue-template-compiler` version](https://github.com/radiantearth/stac-browser/blob/master/package.json#L66) to `^2.6.12`. 

Are these errors reproducible? This is running on an Ubuntu environment through Windows Subsystem for Linux.

**Comment by m-mohr** [comment]
I'm not sure about the cleaning issue, but indeed the versions of vue and vue-template-compiler should always be the same in the package.json, otherwise you get the mentioned error. That should be improved, @lossyrob.

**Comment by lossyrob** [comment]
@charlesbluca thanks for the issue. I was able to reproduce this.

I bumped the vue-template-compiler version and also forced a later version of `fsevents`, which [adds node 12+ compatibility](https://github.com/microsoft/chokidar/pull/1), in #55. This fixes the issue for me.

Would you be able to test that PR and let me know if this solves both the `cannot delete dist` and `vue-template-compiler` issues for you?

**Comment by lossyrob** [comment]
Changes merged, please let me know if you still are experiencing issues and we can reopen if so
