### ISSUE TITLE
Publish on npm / Reccommended way to add STAC Browser to existing Vue website?

### ISSUE THREAD

**Issue by charlesbluca** [radiantearth/stac-browser#62]
I am trying to publish an instance of STAC Browser as a subdirectory to an [existing Vue website published through Netlify.](https://github.com/pangeo-forge/pangeo-forge-vue-website)

What is the best way to do this that allows us to easily pull changes happening in this repo (such as additional features relating to Zarr)? To my knowledge, there isn't a package on npm to add as a dependency to the existing project, so I was planning to deploy the STAC Browser separately from the main website. For handling new changes to the browser, I figured I could either:

- Make a fork of this repo and have Netlify deploy from there, pulling changes as they come
- `git clone` the version of STAC Browser I want as part of the Netlify deployment process

Would these be my best options, or is there an easier way to do this?

cc: @rabernat

**Comment by m-mohr** [comment]
It's not unlikely that we'll do an npm release in the next time. One thing I'd like to accomplish at some point is #17, which would hopefully allow to include the Browser directly into Vue sites.

**Comment by charlesbluca** [comment]
Good to know - feel free to let me know if we can collaborate in any way to get this done.

**Comment by m-mohr** [comment]
Hey @HamedAlemo, is there a Radiant Earth or STAC organization on NPM to publish JavaScript libraries on? Otherwise I could also just publish it as stac-browser without parent organization.

**Comment by HamedAlemo** [comment]
Hey @m-mohr, we have a Radiant one. I just invited you to Radiant org on npm. 
Thanks.

**Comment by m-mohr** [comment]
@charlesbluca My plan is to release to npm in the next one or two weeks with some additonal bug fixes but everything else as it is. Do you just need the npm release for now? Ot is there anything else I can do now? The Vue component integration as discussed in #17 will take a bit longer though.

**Comment by charlesbluca** [comment]
I think the npm release as is should work well for our purposes now - we may want to use specific components with our own styling later on, but for now just an instance of STAC browser is fine.

Thank you for your help with this!

**Comment by m-mohr** [comment]
I've just released the package to npm: https://www.npmjs.com/package/@radiantearth/stac-browser
It can be installed through the normal means, but I'm not sure how useful it actually is. You can't run any of the STAC Browser specific CLI commands, just include the Vue components. I'll work on making the npm release more useful after I've migrated to vue-cli.

**Comment by charlesbluca** [comment]
Great! Thanks for keeping me updated with this.
