### ISSUE TITLE
multi-polygons as extent

### ISSUE THREAD

**Issue by sbrunato** [radiantearth/stac-browser#64]
Hello,
I have a collection with a multi-polygon as geometry. From https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#spatial-extent-object it seams that the extent should a list containing each polygon's bounds. Something like:
```json
"extent":{
  "spatial":{
    "bbox":[
      [-4.592349819344776,42.34338471126569,8.099278598674744,51.14850617126183],
      [-54.524754197799716,2.0533891870159806,-51.65779741067889,5.756548163267765],
      [8.544212680707773,41.380006822264455,9.560016310269134,43.00998484961471]
    ]
  },
```
But this way, stac-browser only plots the first bbox in the collection map:
![image](https://user-images.githubusercontent.com/61419125/104043896-cb46c580-51dc-11eb-9db8-efa6795b9fe9.png)

I am running stac-browser latest version from github (2020-11-18)

**Comment by m-mohr** [comment]
Yes, until a very recent change only a single bbox was allowed and STAC Browser is not up-to-date. I guess it's easy to implement as you just need to put a loop around some existing code, so I'm happy to accept a PR, too.

**Comment by m-mohr** [comment]
I've implemented support for multiple temporal and spatial extents in Collections.
