### ISSUE TITLE
Flesh out readme with a bit more on how to use STAC Browser locally

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-browser#70]
I was about to do a quick PR, but then realized I'm not totally sure if I have the right approach.

I've been using `npx http-server --cors='*' <folder with STAC in it>`. But then I saw the line about a proxy server, and not sure if I could do that. It sounds promising, but I'm not sure how I 'run the proxy server'. 

Maybe the info is all there - I'm a bit dense with this stuff. But perhaps a section that is just 'using STAC browser with a local STAC'.

**Comment by m-mohr** [comment]
That must be a relatively new option I'm not using myself (yet). I'm not exactly sure what it does myself and need to dig into the code to understand what it is exactly meant to do. I'll eventually add details on local usage for sure.
