### ISSUE TITLE
Option to use more human friendly URLs

### ISSUE THREAD

**Issue by schwehr** [radiantearth/stac-browser#72]
Is there a way to use more human friendly URLs?  e.g. this is tough:

https://gee.stac.cloud/51qArHkZKaNd6FYTdZ9A4vDHdpjQy?t=bands

For this asset:

https://earthengine-stac.storage.googleapis.com/catalog/AHN_AHN2_05M_RUW.json

Especially when testing locally. 

For things that are in subdirs like this, it makes sense, but I understand that catalogs can really be any shape as it's just urls.

A little prototype:

- root: https://earthengine-stac-experimental.storage.googleapis.com/catalog-v005/catalog.json
- collection: https://earthengine-stac-experimental.storage.googleapis.com/catalog-v005/USGS/GAP/USGS_GAP_CONUS_2011.json

It would be great to be able to do this or something similar

http://localhost/USGS/GAP/USGS_GAP_CONUS_2011

**Comment by m-mohr** [comment]
No, not yet, but I'm looking into it for STAC browser 2.0. The issue for it is #46.

**Comment by schwehr** [comment]
Sorry I didn't see the other issue before reporting.
