### ISSUE TITLE
STAC Leaflet plugin(s)

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#80]
Requirements for STAC Browser:

Part 1 (basically a STAC vector layer):
1. Show location of a STAC Item (GeoJSON geometry)
2. Show location of a STAC Collection (an overall bbox, potentially multiple smaller bboxes inside the overall bbox)
3. Show locations of STAC API Collections (multiple bboxes, clicking a bbox should emit an event)
4. Show locations of STAC API Items (multiple geometries, clicking a geometry should emit an event)

Part 2 (basically an addition to point 1 above):
- Read and display COGs and GeoTiffs
    - Client-side and/or through a tiler [XYZ] (configurable)
- Select/show specific bands (through Leaflet controls)
    - Optimizations based on eo:bands/raster:bands
- If no COG / GeoTiff is available, show thumbnail (from links or assets) instead (location from bbox)

Additional ideas:
- Show basemap based on STAC metadata #79 (part 1)
- Integration with geotiff.io or some feature of it in STAC Browser? (part 2)
- Swipe
- Opacity
- Other file formats?

Features that can be added via available plugins:
- Fullscreen: Leaflet.fullscreen
- Persist state: leaflet-hash / leaflet-view-meta

**Comment by m-mohr** [comment]
@DanielJDufour We may want to collaborate and extend [this class](https://github.com/radiantearth/stac-browser/blob/v3/src/stac.js), which hopefully helps to share code between STAC Browser and the Leaflet plugins?!

**Comment by DanielJDufour** [comment]
Thanks. Looks promising. I'll keep you updated :-)

**Comment by m-mohr** [comment]
Has been released.
