### ISSUE TITLE
Metadata sidebar shows UTC Temporal Extents as localtime

### ISSUE THREAD

**Issue by ashleysommer** [radiantearth/stac-browser#85]
If I have UTC temporal extents: 1st Feb 2012 00:00:00 to 31st Dec 2012 23:59:59
It will show in the browser in my local time: 1st Feb 2012 10:00am to 1st Jan 2013 9:59am.
![image](https://user-images.githubusercontent.com/402468/126577250-b69d0da4-0fb8-4933-9b77-b95660e7f89c.png)

I don't think this is correct behaviour.

**Comment by m-mohr** [comment]
Well, it's still the correct timestamp. One could argue whether local time should be used or UTC though. I have no strong preference here and would be okay to change to UTC.

**Comment by m-mohr** [comment]
The next version will show UTC times with local formatting.
