### ISSUE TITLE
(Better) support for Data Cube extension

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#87]
STAC Browser 3 is completely rewritten and needs some work to get the ZARR implementation working again. Probably not too much work, but needs to be adapted to the new design at least.

**Comment by cisaacstern** [comment]
@m-mohr, a few points for clarification/discussion, and please forgive me if any of the following are obvious, as I'm relatively new to both Vue and STAC.

1. Is linking `.zmetadata` as an Asset with `{"roles": ["zarr-consolidated-metadata"]}` the officially recommended way to reference a zarr consolidated metadata file in STAC, as suggested by [components/common.js#L262](https://github.com/radiantearth/stac-browser/blob/ac93c4f29d784054f843c029f07bba50d73b8a82/src/components/common.js#L262)?
2. If so, is this recommendation recorded anywhere outside of the STAC Browser repo (i.e., in STAC itself, or a STAC extension)?
3. More broadly, it seems that zarr metadata may often have considerable/complete overlap with `cube:dimensions` and `cube:variables` defined according to https://github.com/stac-extensions/datacube?
    - If so, for STAC Browser 3, might it be worth considering deprecating the `ZarrMetadataTab` in favor of a `DatacubeExtensionTab`?
    - This puts an additional burden on the STAC Browser host to transform zarr metadata into  `cube:dimensions` and `cube:variables` via https://github.com/TomAugspurger/xstac or similar, but perhaps has the advantage of being less "vendor"-specific, and more generalizable?
    - I'd imagine a hypothetical `DatacubeExtensionTab` would render `cube:dimensions` and `cube:variables` comparable to how they're presented in https://planetarycomputer.microsoft.com/dataset/daymet-monthly-hi


cc @TomAugspurger @rabernat in case they have any thoughts to add

**Comment by m-mohr** [comment]
> 1. Is linking `.zmetadata` as an Asset with `{"roles": ["zarr-consolidated-metadata"]}` the officially recommended way to reference a zarr consolidated metadata file in STAC

I guess it is, but that's something the ZARR community should eventually propose and persist and maintain somewhere (as a STAC extension?). Until then I'll stick to what we have and check that the array contains this specific key, so that you could also add more to the array without issues (e.g. the more general "metadata").

> 2. If so, is this recommendation recorded anywhere outside of the STAC Browser repo (i.e., in STAC itself, or a STAC extension)?

See above.

> 3. More broadly, it seems that zarr metadata may often have considerable/complete overlap with `cube:dimensions` and `cube:variables` defined according to https://github.com/stac-extensions/datacube?

cube:variables is pretty new and the whole data cube extension may mirror the content of the zarr metadata for non-ZARR tooling, but I guess it's still a good idea to provide the ZARR metadata directly for the ZARR tooling, right?

>    * If so, for STAC Browser 3, might it be worth considering deprecating the `ZarrMetadataTab` in favor of a `DatacubeExtensionTab`?

There won't be Tabs anymore in STAC Browser 3, we'll try to figure out ways to integrate such things better. But yeah, it might be. In the end it depends on you, whether you can model with the STAC Data Cube Extension good enough. STAC Browser 3 will render Data Cube details by default, so this would help to decrease maintenance if we can get rid of specific component implementations, e.g. for ZARR. Generalization may bring the benefit of better tooling support, but if something is too general we may loose some other benefits. Again, this is something the ZARR community should propose (and discuss with the STAC community).

>    * This puts an additional burden on the STAC Browser host to transform zarr metadata into  `cube:dimensions` and `cube:variables` via https://github.com/TomAugspurger/xstac or similar, but perhaps has the advantage of being less "vendor"-specific, and more generalizable?

Yes, see above.

>    * I'd imagine a hypothetical `DatacubeExtensionTab` would render `cube:dimensions` and `cube:variables` comparable to how they're presented in https://planetarycomputer.microsoft.com/dataset/daymet-monthly-hi

Indeed. I'm working on it.

**Comment by m-mohr** [comment]
@sharkinsspatial I heard you talking about ZARR and STAC Browser today. Could you give some more insights? I'm wondering how your work on ZARR and the ZARR (re-)implementation relate and whether I can help with implementating it for STAC Browser, whether we need to discuss anything or whether I can depriorize this if you come up with other solutions? Also happy to jump on a call or so. Thanks!

**Comment by cisaacstern** [comment]
@m-mohr, thank you for your detailed responses to my questions above. Apologies that I haven't gotten to reply sooner. I will be curious to hear from Sean if he has a diverging viewpoint, but from my perspective working on http://pangeo-forge.org/catalog, I don't have a high priority for Zarr support in STAC Browser 3. We are planning to translate Zarr metadata into Datacube Extension fields, so Datacube support will cover our use case.

As an aside, we are be planning to represent Zarr stores as STAC Items (not Collections), so it will be ideal for us if STAC Browser 3 is aware of both the Item and Collection variants of the Datacube extension. (You are likely already planning this, but just thought I'd mention it for clarity's sake.)

Thanks so much for all of your work on this incredible resource.

**Comment by m-mohr** [comment]
Thanks for the insights. So I'll remove the Zarr related code from STAC Browser for now.
I'm planning to better implement the data cube extension soon and it will work in Items and Collections.

**Comment by sharkinsspatial** [comment]
@m-mohr Apologies that we didn't have more time to clarify in the call today.  I'd concur with @cisaacstern here.  There was some discussion within the `pangeo-forge` group about what method we should use to represent dimension information in STAC Browser but it sounds like we have agreed on relying on the Datacube extension.  Echoing @cisaacstern 's comment thank you for delving into this massive refactoring effort 🙌 .

**Comment by m-mohr** [comment]
Closing in favor of #115 and #113
