### ISSUE TITLE
Tiled Stretching on Previews (V2)

### ISSUE THREAD

**Issue by jlaura** [radiantearth/stac-browser#90]
It looks like the tile server is applying per tile image stretch when the data are 32bit. For example, the DTM below is 32bit and we see distinct image boundaries due to stretching

<img width="766" alt="Screen Shot 2021-08-16 at 9 33 23 AM" src="https://user-images.githubusercontent.com/2105468/129598194-55285d11-9356-4dcd-aa2c-8c2ca52e94a9.png">

When we swap to the 8bit hillshade, the preview looks as one would expect.

<img width="762" alt="Screen Shot 2021-08-16 at 9 33 34 AM" src="https://user-images.githubusercontent.com/2105468/129598261-e7efea41-2272-4b63-9e54-0f1446b1c79a.png">

**Comment by m-mohr** [comment]
Could you provide the links for those two Items, please?

**Comment by jlaura** [comment]
:+1:

[Link](https://stac.astrogeology.usgs.gov/browser/#/item/3q52Dkr5nBe3g684y9fzjwTFMjyyQ66QitBuDrNggEBLhzMJFUvkYYXvSppyx71tvJpVWQkxLgEHK/EfcLDDAkyqgqdedCsXSnoX9MeZsTMNV7GPJBA97Dvo6kpKygWCR24krrFY4PdTr2MhPGHKEL5uXn5eAX36uqBadQgTsmF/4Ua8RY2czjpMAi8zD1iqiZQznkdDNK21C8q9MmoiRWUN2nA79UgjFzX8ugyWXaEZoc6UPXwDzjanALazzy9hoiyU9FAyiKgfyXidEVFncKM2p1VNzH4xhx4hGq2iW7Y8QbLNe7aqAHSs8WzQ37ZEvrNwNnLXHvhCG9tkeM1a2jxrysUDBUU54kjP9BbUAzZnHPX6E2TamUh51wQQC2NdHUEGpVjDnPcBsftAosR3bK?si=0#10/7.620170/163.679505)

Maybe we should be running a tile server for these data and serving them ourselves?

**Comment by m-mohr** [comment]
Thanks! Let's check first whether client-side rendering does a better job, will follow up in the next days.

Just for my personal reference, these are the corresponding links in STAC Browser v3:
- https://radiantearth.github.io/stac-browser/#/external/asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W_DEM.json
- https://localhost:8080/external/asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W_DEM.json

Right now, no data is shown.

**Comment by m-mohr** [comment]
Sorry, I've never followed up on this issue. Nothing has changed in the client-side rendering so far, the data is still now shown. Making them work is out of scope for STAC Browser and would likely need to be reported to the underlying library georaster-layer-for-leaflet. I agree with you that right now it's probably the best idea to run a tile server for these data and serve the tiles yourselves.
