### ISSUE TITLE
Some issues with DEAfrica items

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#93]
Example: https://radiantearth.github.io/stac-browser/#/external/explorer.digitalearth.africa/stac/collections/gm_s2_annual/items/0030c11d-662c-5cbf-bdb3-275e6aa186a0

- [x] proj:shape/transform should be rendered better
- [x] expanding all data assets is over the top. Find a better alternative.
- [x] odc category should be OpenDataCube
- [x] External "Additional Resources" have broken links
- [x] The title field should not be shown in metadata but instead be used in the h1 header

**Comment by m-mohr** [comment]
All fixed! Let me know if you encounter more issues. @alexgleith

**Comment by alexgleith** [comment]
Looks good to me, thanks @m-mohr!
