### ISSUE TITLE
Root catalogs shown (instead of Items)

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#94]
@m-mohr very nice! you did a lot of improvements both in terms of layout and functionalities (I appreciate the search and filter UI).
The pagination seems to work. 

I did find the follwing issue:

1. Load a STAC catalog/api e.g. https://radiantearth.github.io/stac-browser/#/external/data.geo.admin.ch/api/stac/v0.9/
2. Click on a Catalog 
3. The collection metadata is shown but on the right all catalogs in the API are shown instead of Items
4. One has to go one step back and click again on a catalog to have then the Items loaded

Same behaviour if you share the collection via the share tool; e.g.: https://radiantearth.github.io/stac-browser/#/external/data.geo.admin.ch/api/stac/v0.9/collections/ch.swisstopo.swissalti3d

_Originally posted by @p1d1d1 in https://github.com/radiantearth/stac-browser/issues/34#issuecomment-913683242_

**Comment by m-mohr** [comment]
Thanks @p1d1d1 for the report. I've also seen this happening. I'll investigate and fix this!

**Comment by m-mohr** [comment]
Fixed

**Comment by p1d1d1** [comment]
Great! Many thanks
